---
title: <center><font face="Baskerville Old Face">**A Study on Birds Breeding Pairs**</font></center>
output: html_document
---
<div id="backhome"><a href="index.html"><i class="fa fa-home" aria-hidden="true"></i></a></div>
<div id="back"><a href="Projects.html"><i class="fa fa-undo" aria-hidden="true"></i></a></div>

Still under constructions.

#<font face="Baskerville Old Face">(I) Background</font>
<font face="Times New Roman" color=black size=4>

- Instructor: Michael Lavine
- This project has been done in an undergraduate statistics courses, *Regression & Analysis of Variance*.
- Team members: Da Lu, Dan Wang, YangJunqing Qiao, Kweku Fynn
- Date: Apr/28/2017


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The data set, which was provided by *Martin Cody, PhD, UCLA, Department of OBEE*, was downloaded from http://www.stat.ucla.edu/projects/datasets/birds.dat.  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The keywords for the data set were *Birds*, *Diversity*, *Vegetation Structure* and *Density*.  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The following quotes are the descriptions of the data set.

>**1. GENERAL EXPLANATION OF THE STUDY (done by *Martin Cody*)**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The accompanying data set is from a study on the diversity patterns of bird communities in North American oak woodlands and Australian eucalyptus woodlands. Because the study's entire data set is very large, the only data included here are from sites in Californian oak woodlands. Very roughly, the data provide information about the location, vegetation structure, and number of species of breeding bird pairs at various sites throughout California's woodlands. The term "woodlands" refers to moderately thick forests with uneven canopy cover, and the numerical indexes of vegetation structure provided by the data can be thought of as a kind of scientific description of the overall look of a forest - the height of its trees, the density of its foliage, the variation from forest floor to forest ceiling.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Although the study itself was primarily concerned with somewhat complex comparisons between the bird diversity patterns in North America and Australia, these data can be used to study ecological aspects of the bird diversity problem - a subject emphasized in much of the earlier literature on species diversity. These ecological aspects focus on predicting the number and density of different bird species from information about the vegetation structure and location of a site, particularly its latitude. Thus the data can be used to answer the following kinds of questions: Are there more species of birds in denser forests? Are birds concentrated more densely in areas where vegetation is more dense? In general, is there more diversity in locations at higher latitudes, or lower latitudes? And, perhaps most importantly, which technical measure of vegetation structure is the best predictor of the number of bird species in a forest. Many other, more subtle questions can be explored using these data as well.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Explanations of the measures of vegetation structure and other variables are given below. It should be noted, finally, that the natural logarithms of variables, rather than the raw variables as given in the data, are generally used when examining relationships or identifying good predictors. Thus the correlation between the log of the "Profile Area" and the number of bird species in a forest - to take a concrete example - is stronger than the correlation between the "Profile Area" and the number of species.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This study has not yet been published (12/09/99).  
>**2. BRIEF DESCRIPTION OF THE DATA**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Data were gathered at 40 different California oak woodland sites. Most of the data were collected in spring, during the bird breeding season, in 1994.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The sites were around 5 hectares in size - the equivalent of about 12 acres, or 0.019 square miles - and were situated in relatively homogeneous habitat. At least three visits were made to each site, and the number of breeding pairs of each bird species were counted by sight and by analyzing sound recordings.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Measurements of vegetation structure were also made during the visits.  
>**3. HOW TO USE THE DATA FILES**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The data file is a comma delimited text file. Missing data are indicated by periods ("."). The following list explains each of the seven variables. To understand the measurements of vegetation structure, you'll need the concept of a forest's vegetation density at a particular height. Roughly, this is just a measure of how thick the foliage is at a given cross-sectional height. To attach a number to this thickness, two researchers position themselves at the height whose vegetation density they wish to measure and one holds a flat wooden board and moves away from the other. The stationary researcher then notes the distance to "semi-obscurity": how far away his partner is when the view of the board is half obscured by foliage. Since this distance will be smaller in thicker foliage, its reciprocal is taken as the measure of vegetation density. Thus higher numbers will correspond to thicker foliage.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**1) ELEVATION**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The height of the site above sea level. Given in meters.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**2) PROFILE AREA**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roughly, a measure of the total amount of foliage at a site. Technically, this number is obtained by plotting vegetation density versus height above ground and taking the total area under the graph. The units, however, are not typical area units, as vegetation density is the reciprocal of a distance; the units are specially designed to measure profile area, and are called f.p. units (foliage profile units).  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**3) HEIGHT**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roughly, the height of the top of the forest canopy. Technically, the height above which horizontal distance to semi-obscurity exceeds 30 meters. Given in meters.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**4) HALF-HEIGHT**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roughly, the height that divides total foliage in two: half the forest is above it, and half below. Technically, the median of the graph of vegetation density versus height. Given in meters.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**5) LATITUDE**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The latitude of the site. Given in degrees.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**6) LONGITUDE**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The longitude of the site. Given in degrees.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**7) NO. SPECIES**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The number of different species of breeding bird pairs.  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**8) TOTAL DENSITY**  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A measure of the bird population density. It is simply the number of pairs of birds per hectare.

</font>

#<font face="Baskerville Old Face">(II) Introduction</font>
<font face="Times New Roman" color=black size=4>

- This data is from a study done on the number of breeding pairs of birds in 40 locations around the American Pacific coastline as well as closer inland. Taken during the spring of 1994, the sites were all around 5 hetacres in size and situated in relativly homogenous habitats. The number breeding pairs of bird species was counted by sight and by analyzing sound recordings. The variables are defined by the researchers as follows:
    - `SITE`: The place where the data were collected.
    - `Elevation`: The height of the site above sea level. Given in meters.
    - `Profile.Area`: Roughly, a measure of the total amount of foliage at a site. We consider it as the density of forest at certain height.
    - `Height`: Roughly, the height of the top of the forest canopy. Technically, the height above which horizontal distance to semi-obscurity exceeds 30 meters(a height from which line of sight is over 30 meters).
    - `Half.height`: Roughly, the height that divides total foliage in two: half the forest is above it, and half below. Technically, the median of the graph of vegetation density versus height. Given in meters.
    - `Latitude`: The latitude of the site. Given in degrees.
    - `Longitude`: The longitude of the site. Given in degrees.
    - `No..Species`: The number of different species of breeding bird pairs.
    - `Total.density`: A measure of the bird population density. It is simply the number of pairs of birds per hectare.
- There is data missing from the `Elevation`, `Profile.Area`, `Height`, and `Half.height` variables. The missing points of elevation seem to be random. However, the missing data points for `Profile.Area`, `Height`, and `Half.height` follow the following conditions:
    - A site missing its `Half.height` will also not have its `Profile area` and vice versa.
    - If a site is missing its `Height` variable, it will also be missing its `Profile.Area` and `Half.height` variables.
    - A likely explanation for this is that `Profile.Area` is related in some way to `Half.height`, according to the description of the variables, `Half.height` and `Profile.Area` are both calculated from vegetation density with respect to height. So it would also make sense that in the cases where `Height` was not calculatable that the data points for `Profile.Area` and `Half.height` are missing as well. In our calculations and work, we chose to simply ignore missing values in our plots and for fitting our models.

</font>

```{r}
library(knitr)
bird=read.table("http://www.stat.ucla.edu/projects/datasets/birds.dat",header=TRUE,sep=",",fill=TRUE)
kable(bird,align="c")
```

