---
title: "Course Material"
output:
  html_document:
    toc: TRUE
    toc_float: 
      collapsed: FALSE
    toc_depth: 2
---

<style>
h1 {font-size: 28px; color: black; font-weight: bold; text-align: center;}
h1.title {color: black; text-align: center;}
h2 {font-size: 20px; color: black; font-weight: bold; font-style: italic;}
p {font-size: 16px; color: black;}
ol {font-size: 16px; color: black;}
ul {font-size: 16px; color: black;}
</style>

---

#STSCI 5065 - Big Data Management and Analysis
##Lecture Slides
1. [Concepts of Big Data and Hadoop](CU/5065/Lec01.pdf)
    - [Lecture 1 Note](CU/5065/Summary01.html)
    - [Install CentOS in VirtualBox](CU/5065/Lec01.1.pdf)
2. [Basic Linux Commands](CU/5065/Lec02.pdf)
    - [Lecture 2 Note](CU/5065/Summary02.html)
3. [Basic Vi Commands](CU/5065/Lec03.pdf)
    - [Lecture 3 Note](CU/5065/Summary03.html)
4. [The Hadoop Distributed Filesystem (HDFS)](CU/5065/Lec04.pdf)
    - [Lecture 4 Note](CU/5065/Summary04.html)
5. [Introduction to Hortonworks Sandbox](CU/5065/Lec05.pdf)
    - [Lecture 5 Note](CU/5065/Summary05.html)
6. [MapReduce (M/R) Part 1](CU/5065/Lec06.pdf)
    - [Lecture 6 Note](CU/5065/Summary06.html)
7. [MapReduce (M/R) Part 2](CU/5065/Lec07.pdf)
    - [Lecture 7 Note](CU/5065/Summary07.html)
8. [Introduction to Apache Hive 1](CU/5065/Lec08.pdf)
    - [Lecture 8 Note](CU/5065/Summary08.html)
9. [Introduction to Apache Hive 2](CU/5065/Lec09.pdf)
    - [Lecture 9 Note](CU/5065/Summary09.html)
10. [Introduction to Apache Hive 3](CU/5065/Lec10.pdf)
    - [Lecture 10 Note](CU/5065/Summary10.html)
11. [Introduction to Apache Hive 4](CU/5065/Lec11.pdf)
    - [Lecture 11 Note](CU/5065/Summary11.html) (pending)


##Homeworks
1. [Homework 1](CU/5065/HW1.pdf)
    - Due: Feb/18/2019 at 11:59PM
    - [Summary](CU/5065/HW1_Summary.html)
2. [Homework 2](CU/5065/HW2.pdf)
    - Due: Mar/12/2019 at 11:59PM
    - Data: [shakespeare](CU/5065/shakespeare.txt) (.txt)
    - [Summary](CU/5065/HW2_Summary.html)

##Quizzes
1. [Quiz 1 with solutions](CU/5065/Quiz1_S.pdf)
2. [Quiz 2 with solutions](CU/5065/Quiz2_S.pdf)
3. [Quiz 3 with solutions](CU/5065/Quiz3_S.pdf)

##Data Files
- [1901-1](CU/5065/1901-1) (.File)
- [1901](CU/5065/1901) (.File)
- [1902](CU/5065/1902) (.File)
- [1901-1902](CU/5065/1901-1902) (.File)
- [1990](CU/5065/1990.zip) (.zip)
- [1991](CU/5065/1991.zip) (.zip)
- [empdata-comma](CU/5065/empdata-comma.txt) (.txt)
- [empdata-tab](CU/5065/empdata-tab.txt) (.txt)
- [empdata-us-ca](CU/5065/empdata-us-ca.txt) (.txt)
- [empdata-us-il](CU/5065/empdata-us-il.txt) (.txt)
- [empdata-us-ny](CU/5065/empdata-us-ny.txt) (.txt)

---

#STSCI 4060 - Python Programming and its Applications in Statistics
##Lecture Slides
1. [Lecture 1](CU/4060/Lec01.pdf)
    - [Note 1-1](CU/4060/LectureNote1-1.html): Calculator, Basic Data Types
    - [Note 1-2](CU/4060/LectureNote1-2.html): String Functions, Lists
    - [Note 1-3](CU/4060/LectureNote1-3.html): List Functions, Matrices, Tuples, Dictionaries, Dictionary Functions
    - [Note 1-4](CU/4060/LectureNote1-4.html): Sets, Set Operations, Set Functions, Data Type Comparison, Operators
2. [Lecture 2](CU/4060/Lec02.pdf)
    - [Note 2-1](CU/4060/LectureNote2-1.html): Built-in Functions, More on Creating Dictionaries
    - [Note 2-2](CU/4060/LectureNote2-2.html): Importable Functions, User-Defined Functions, Polymorphism, Variable Scopes, Starred-Argument Syntax
    - [Note 2-3](CU/4060/LectureNote2-3.html): Files, Class and Objects
3. [Lecture 3](CU/4060/Lec03.pdf)
    - [Note 3](CU/4060/LectureNote3-1.html): `import`, `assert`, `if`, `for`, `while`, `try: ... except`, User-Defined Exceptions
4. [Lecture 4](CU/4060/Lec04.pdf)
    - [Note 4](CU/4060/LectureNote4-1.html): Stack, Queue, Linked List, Tree
    - [LinkedList實現](CU/4060/LectureNote4-2.html)
    - [BinaryTree實現&相關](CU/4060/LectureNote4-3.html)
5. [Lecture 5](CU/4060/Lec05.pdf)
    - [Note 5](CU/4060/LectureNote5-1.html): Lambda function, Regular expression, Graphics
6. [Lecture 6](CU/4060/Lec06.pdf)
    - [Note 6-1](CU/4060/LectureNote6-1.html): Plotting, Bar Chart, Graphical user interface (GUI), Linear regression plot, 3-D plotting with plotting modules
7. [Lecture 7](CU/4060/Lec07.pdf)
8. [Lecture 8](CU/4060/Lec08.pdf)


##Homeworks
1. [Homework 1](CU/4060/HW1.pdf)
    - Due: Feb/15/2019 at 11:59PM
    - [Summary](CU/4060/STSCI 4060 - HW 1.html)
    - [Solutions](CU/4060/HW1_S.7z) (.7z)
2. [Homework 2](CU/4060/HW2.pdf)
    - Due: Mar/2/2019 at 11:59PM
    - Data: [AboutCornell](CU/4060/AboutCornell.txt) (.txt)
    - Data: [stock](CU/4060/stock.txt) (.txt)
    - [Summary](CU/4060/STSCI 4060 - HW 2.html)
    - [Solutions](CU/4060/HW2_S.7z) (.7z)
3. [Homework 3](CU/4060/HW3.pdf)
    - Due: Mar/12/2019 at 11:59PM
    - [Summary](CU/4060/STSCI 4060 - HW 3.html)
    - [Solutions](CU/4060/HW3_S.7z) (.7z)
4. [Homework 4](CU/4060/HW4.pdf)
    - Due: Mar/26/2019 at 11:59PM
    - Data: [unequal](CU/4060/unequal.txt) (.txt)
    - [Summary](CU/4060/STSCI 4060 - HW 4.html)



##Data Files
- [points_scatplot1](CU/4060/points_scatplot1.txt) (.txt)
- [ring](CU/4060/ring.txt) (.txt)
- [bee_proteins](CU/4060/bee_proteins.txt) (.txt)

##Quizzes
1. [Quiz 1 with solutions](CU/4060/Quiz1_S.pdf)
2. [Quiz 2 with solutions](CU/4060/Quiz2_S.pdf)
3. [Quiz 3 with solutions](CU/4060/Quiz3_S.pdf)

##Books and References
- [Hands-on Python](CU/4060/Books and References/Hands-on Python.pdf)
- [Python Tutorial](CU/4060/Books and References/Python Tutorial.pdf)
- [Graphics Library Quick Reference](CU/4060/Books and References/Graphics Library Quick Reference.pdf)
- [Graphics Module Reference](CU/4060/Books and References/Graphics Module Reference.pdf)
- [python_reg_expressions](CU/4060/Books and References/python_reg_expressions.pdf)
- [numpy-reference](CU/4060/Books and References/numpy-reference.pdf)
- [HTML_Tag_List](CU/4060/Books and References/HTML_Tag_List.pdf)
- [The Lorenz System](CU/4060/Books and References/The Lorenz System.pdf)

##Software
- [kompozer-0.8b3.en-US.win32](CU/4060/Software/kompozer-0.8b3.en-US.win32.exe) (.exe)
- [kompozer-0.8b3.en-US.mac-universal](CU/4060/Software/kompozer-0.8b3.en-US.mac-universal.dmg) (.dmg)
- [commonFormFields](CU/4060/Software/commonFormFields.html)
- [findMaxLength](CU/4060/Software/findMaxLength.py) (.py)
- [localCGIServer](CU/4060/Software/localCGIServer.py) (.py)
- [graphics](CU/4060/Software/graphics.pyc) (.pyc)

---

#STSCI/ORIE 4630 - Operations Research Tools for Financial Engineering
##Lecture Slides
- Week 1
    1. Tu: [Jan/22](CU/4630/Lec01.html)
    2. Th: [Jan/24](CU/4630/Lec02.html) 
- Week 2
    3. Tu: [Jan/29](CU/4630/Lec03.html)
    4. Th: [Jan/31](CU/4630/Lec04.html)
- Week 3
    5. Tu: [Feb/5](CU/4630/Lec05.html)
    6. Th: [Feb/7](CU/4630/Lec06.html)
- Week 4
    7. Tu: [Feb/12](CU/4630/Lec07.html)
    8. Th: [Feb/14](CU/4630/Lec08.html)
- Week 5
    9. Tu: [Feb/19](CU/4630/Lec09.html) (pending pictures)
    - Th: Feb/21, Midterm 1
- Week 6
    - Tu: Feb/26, Holiday
    10. Th: [Feb/28](CU/4630/Lec10.html) (pending pictures and revision)
- Week 7
    11. Tu: [Mar/5](CU/4630/Lec11.html) (pending revision)
    12. Th: [Mar/7](CU/4630/Lec12.html) (pending revision)
- Week 8
    13. Tu: [Mar/12](CU/4630/Lec13.html) (pending revision)
    14. Th: [Mar/14](CU/4630/Lec14.html) (pending revision)
- Week 9
    15. Tu: [Mar/19](CU/4630/Lec15.html) (pending)
    16. Th: [Mar/21](CU/4630/Lec16.html) (pending)

##Homeworks
1. [Homework 1](CU/4630/HW1.pdf)
    - data: [returns](CU/4630/returns.csv) (.csv)
    - Due: Feb/5/2019, Tuesday
    - [HW1](CU/4630/HW1.html)
2. [Homework 2](CU/4630/HW2.pdf)
    - data: [returns](CU/4630/returns.csv) (.csv)
    - Due: Feb/12/2019, Tuesday
    - [HW2](CU/4630/HW2.html)
3. [Homework 3](CU/4630/HW3.pdf)
    - data: [returns](CU/4630/returns.csv) (.csv)
    - Due: Feb/19/2019, Tuesday
    - [HW3](CU/4630/HW3.html)
4. [Homework 4](CU/4630/HW4.pdf)
    - data: [returns](CU/4630/returns.csv) (.csv)
    - data: [prices](CU/4630/prices.csv) (.csv)
    - Due: Feb/28/2019, Thursday
    - [HW4](CU/4630/HW4.html)
5. [Homework 5](CU/4630/HW5.pdf)
    - data: [returns](CU/4630/returns.csv) (.csv)
    - Due: Mar/12/2019, Tuesday
    - [HW5](CU/4630/HW5.html)
6. [Homework 6](CU/4630/HW6.pdf)
    - data: [returns](CU/4630/returns.csv) (.csv)
    - data: [3m_treasury_bill_rate](CU/4630/3m_treasury_bill_rate.csv) (.csv)
    - Due: Mar/19/2019, Tuesday
    - [HW6](CU/4630/HW6.html)
7. [Homework 7](CU/4630/HW7.pdf)
    - Due: Mar/28/2019, Thursday
    - [HW7](CU/4630/HW7.html) (pending)



##Exams
- [Midterm 1 Solution](CU/4630/Midterm1_S.pdf)

---

#STSCI 5999 - Applied Statistics MPS Data Analysis Project
##Project Progress
- [Forecasting](CU/5999/Forecasting.html)
- [Forecasting Function](CU/5999/Forecasting_Function.html)

---

#CS 5786 - Machine Learning for Data Science
##Lecture Slides
- Week 1
    - Lecture 1: [Course introduction, Logistics, Dimensionality reduction](CU/5786/Lec01.pdf)
    - Lecture 2: [Dimensionality Reduction, Principal Component Analysis](CU/5786/Lec02.pdf)
    - Demo: [PCA demo - Classroom](CU/5786/classroom_demo.html)
    - Demo: [PCA demo - Smile](CU/5786/smile_demo.html)
    - Handout (Jan/24): [PCA Handout 1](CU/5786/Handout01.html)
    - Lecture Note: 2 & 3 [Principal Component Analysis](CU/5786/LecNote2-3.pdf)
- Week 2
    - Lecture 3: [Principal Component Analysis](CU/5786/Lec03.pdf)
    - Handout (Jan/29): [PCA Handout 2](CU/5786/Handout02.html)
    - Algorithm: [**PCA Algorithm**](CU/5786/Algorithm01.html)
    - Lecture 4: [PCA and Random Projections](CU/5786/Lec04.pdf)
    - Handout (Jan/31): [Random Projections Handout](CU/5786/Handout03.html)
- Week 3
    - Lecture 5: [Random Projections & Canonical Correlation Analysis](CU/5786/Lec05.pdf)
    - Lecture Note: 5 [Random Projections](CU/5786/LecNote5.pdf)
    - Lecture 6: [Canonical Correlation Analysis](CU/5786/Lec06.pdf)
    - Handout (Feb/7): [Canonical Correlations Analysis Handout](CU/5786/Handout04.html)
    - Lecture Note: 6 [Canonical Correlation Analysis](CU/5786/LecNote6.pdf)
- Week 4
    - Lecture 7: [Canonical Correlation Analysis & Kernel PCA](CU/5786/Lec07.pdf)
    - Lecture Note: 7 [Kernel PCA](CU/5786/LecNote7.pdf)
    - Lecture 8: [Kernel PCA & Isomap](CU/5786/Lec08.pdf)
    - Handout (Feb/14): [Kernel Methods & t-SNE](CU/5786/Handout05.html) (pending)
    - Demo: [KPCA demo - Circle](CU/5786/circle_demo.html)
    - Demo: [KPCA demo - Concentric Circles](CU/5786/concentric_circles_demo.html)
- Week 5
    - Lecture 9: [Isomap & t-SNE](CU/5786/Lec09.pdf)
    - Handout (Feb/19): [t-SNE & Spectral Embedding](CU/5786/Handout06.html) (pending)
    - Lecture 10: [Spectral Embedding](CU/5786/Lec10.pdf)
    - Handout (Feb/21): [Spectral Embedding](CU/5786/Handout07.html) (pending)
- Week 6
    - Lecture 11: [Spectral Embedding & Clustering](CU/5786/Lec11.pdf)
- Week 7
    - Lecture 12: [Clustering & Linkage Clustering](CU/5786/Lec12.pdf)
    - Handout (Mar/5): [Clustering: Linkage Clustering](CU/5786/Handout08.html) (pending)
    - Demo: [???]() (pending)
    - Lecture 13: [K-Means Clustering](CU/5786/Lec13.pdf)
    - Lecture Note: 12 & 13 [Clustering, Single-link algorithm, K-means Algorithm](CU/5786/LecNote12-13.pdf)
- Week 8
    - Lecture 14: [Gaussian Mixture Model](CU/5786/Lec14.pdf)
    - Lecture Note: 14 [EM Algorithm for Gaussian Mixture Models and Why EM works](CU/5786/LecNote14.pdf)
    - Demo: [???]() (pending)


##Homeworks
- [Vocareum Link](https://labs.vocareum.com/home/login.php?email=dl947%40cornell.edu)
- [Homework 1](CU/5786/HW1.html)
    - Due: Feb/20/2019 23:59:59 EST
- [Homework 2](CU/5786/HW2.html) (pending)
    - Due: Mar/15/2019 23:59:59 EST
-  
-  

##Exams
- [Placement Exam](CU/5786/PlacementExam.pdf)
    - Due: Jan/31/2019
    - [Summary](CU/5786/Placement_Exam.html)
- Midterm
    - Mar/28/2019 at STL185
- Final
    - May/14/2019 at 7:00PM

---

---

---

#STSCI 5010 - Applied Statistical Computation with SAS
##Syllabus
- Fall 2018 Syllabus

##Lecture Slides
**--- Module 1**

1. [Basic Concepts](CU/5010/Lec1.pdf)
2. [Referencing Files and Setting Options](CU/5010/Lec2.pdf)
3. [Editing and Debugging](CU/5010/Lec3.pdf)
4. [Creating List Reports](CU/5010/Lec4.pdf)
5. [Creating SAS Data Sets From External Files](CU/5010/Lec5.pdf)
6. [Understanding DATA Step Processing](CU/5010/Lec6.pdf)
7. [Creating and Applying User-Defined Formats](CU/5010/Lec7.pdf)
8. [Producing Descriptive Statistics](CU/5010/Lec8.pdf)
9. [Producing HTML Output](CU/5010/Lec9.pdf)
10. [Creating and Managing Variables_new](CU/5010/Lec10.pdf)
11. [Reading SAS Data Sets](CU/5010/Lec11.pdf)
12. [Combining SAS Data Sets](CU/5010/Lec12.pdf)
13. [Transforming data with SAS functions](CU/5010/Lec13.pdf)
14. [Generating Data With Do Loops](CU/5010/Lec14.pdf)
15. [Processing Variables with SAS Arrays](CU/5010/Lec15.pdf)
16. [Reading Raw Data in Fixed Fields](CU/5010/Lec16.pdf)
17. [Reading Free-Format Data](CU/5010/Lec17.pdf)
18. [Reading Date and Time Values](CU/5010/Lec18.pdf)
19. [Creating a Single Observation from Multiple Records](CU/5010/Lec19.pdf)
20. [Creating Multiple Observations From a Single Record](CU/5010/Lec20.pdf)
21. [Reading Hierarchical Files](CU/5010/Lec21.pdf)

**--- Module 2**

22. [Introduction to SAS Enterprise Miner (EM) and Data Visualization](CU/5010/Lec22.pdf)
23. [Cluster Analysis with SAS](CU/5010/Lec23.pdf)
24. [Preparation for Clustering](CU/5010/Lec24.pdf)
25. [Hierarchical Clustering](CU/5010/Lec25.pdf)
26. [Optimization Clustering](CU/5010/Lec26.pdf)

##Homeworks
1. [HW 1](CU/5010/HW1.pdf)
    - data: [admit](CU/5010/admit.sas7bdat) (.sas7bdat)
    - Due: Sep/27/2018 at 11:59PM
    - [Solutions](CU/5010/HW1_S.7z) (.7z)
2. [HW 2](CU/5010/HW2.pdf)
    - data: [FBPandHIV](CU/5010/FBPandHIV.xlsx) (.xlsx)
    - Due: Oct/11/2018 at 11:59PM
    - [Solutions](CU/5010/HW2_S.7z) (.7z)
3. [HW 3](CU/5010/HW3.pdf)
    - data 1: [expenses](CU/5010/expenses.sas7bdat) (.sas7bdat)
    - data 2: [company](CU/5010/company.sas7bdat) (.sas7bdat)
    - Due: Nov/8/2018 at 11:59PM
4. [HW 4](CU/5010/HW4.pdf)
    - Due: Nov/27/2018 at 11:59PM
5. [HW 5](CU/5010/HW5.pdf)
    - data: [flowers](CU/5010/flowers.sas7bdat) (.sas7bdat)
    - Due: Dec/5/2018 at 11:59PM

##Labs
1. [Lab 1](CU/5010/Lab1.pdf)
    - data: [nutrition](CU/5010/nutrition.sas7bdat) (.sas7bdat)
    - Due: Sep/23/2018 at 11:59PM
    - [Solutions](CU/5010/Lab1_S.7z) (.7z)
2. [Lab 2](CU/5010/Lab2.pdf)
    - data 1: [Sales](CU/5010/Sales.txt) (.txt)
    - data 2: [empdata](CU/5010/empdata.sas7bdat) (.sas7bdat)
    - data 3: [demog](CU/5010/demog.sas7bdat) (.sas7bdat)
    - data 4: [visit](CU/5010/visit.sas7bdat) (.sas7bdat)
    - Due: Oct/21/2018 at 11:59PM
    - [Solution](CU/5010/Lab2_S.7z) (.7z)

##Quizzes
1. [Quiz 1 with Solutions](CU/5010/Quiz1_S.pdf)
2. [Quiz 2 with Solutions](CU/5010/Quiz2_S.pdf)
3. [Quiz 3 with Solutions](CU/5010/Quiz3_S.pdf)
4. [Quiz 4 with Solutions](CU/5010/Quiz4_S.pdf)

##Exams
1. [Midterm 1 with Solutions](CU/5010/Exam1_S.pdf)
2. [Midterm 2 with Solutions](CU/5010/Exam2_S.pdf)
3. [SAS Base Exam Practice](CU/5010/SAS_Exam_Practice.pdf)
    - [Solutions](CU/5010/SAS_Exam_Practice_S.pdf)

##SAS Data
1. [workloads](CU/5010/workloads.sas7bdat) (.sas7bdat)
2. [unequal](CU/5010/unequal.sas7bdat) (.sas7bdat)
3. [ring](CU/5010/ring.sas7bdat) (.sas7bdat)
4. [pizza](CU/5010/pizza.sas7bdat) (.sas7bdat)
5. [fish](CU/5010/fish.sas7bdat) (.sas7bdat)
6. [credit](CU/5010/credit.sas7bdat) (.sas7bdat)
7. [bank](CU/5010/bank.sas7bdat) (.sas7bdat)

##SAS Related Files
- [Reference](CU/5010/SAS_Codes.html)
- [Lab 1 log](CU/5010/Lab1_Log.pdf)
- [SAS Certification Exam](CU/5010/SAS_Exam.pdf)

---

#STSCI 5030 - Linear Models with Matrices
##Resources
- [Summary from Year 2016](CU/5030/Notes.pdf)
- [Lecture 0](CU/5030/Lec0.pdf)
- [Syllabus](CU/5030/Syllabus.pdf)
- [Texts Links](CU/5030/TextsLinks.pdf)

##Homeworks
1. Homework 1
    - [Question 1](CU/5030/HW1-Q1.html)
    - [Question 2](CU/5030/HW1-Q2.html)
    - [Question 3](CU/5030/HW1-Q3.html)
    - Data: [BrainWeight](CU/5030/BrainWeight.txt) (.txt)
    - [Solutions](CU/5030/HW1_S.pdf)
2. Homework 2
    - [Question 1](CU/5030/HW2-Q1.html)
    - [Question 2](CU/5030/HW2-Q2.html)
    - [Question 3](CU/5030/HW2-Q3.html)
    - Data: [BrainWeight](CU/5030/BrainWeight.txt) (.txt)
    - [Solutions](CU/5030/HW2_S.pdf)
3. Homework 3
    - [Question 1](CU/5030/HW3-Q1.html)
    - [Question 2](CU/5030/HW3-Q2.html)
    - [Question 3](CU/5030/HW3-Q3.html)
    - [Question 4](CU/5030/HW3-Q4.html)
    - Data: [BrainWeight](CU/5030/BrainWeight.txt) (.txt)
    - Data: [precipitation](CU/5030/precipitation.csv) (.csv)
    - [Solutions](CU/5030/HW3_S.pdf)
4. Homework 4
    - [Question 1](CU/5030/HW4-Q1.html)
    - [Question 2](CU/5030/HW4-Q2.html)
    - [Question 3](CU/5030/HW4-Q3.html)
    - [Question 4](CU/5030/HW4-Q4.html)
    - Data: [airpollution](CU/5030/airpollution.csv) (.csv)
    - Data: [NutritionStdy](CU/5030/NutritionStdy.csv) (.csv)
    - [Solutions](CU/5030/HW4_S.pdf)
5. Homework 5
    - [Question 1](CU/5030/HW5-Q1.html)
    - [Question 2](CU/5030/HW5-Q2.html)
    - [Question 3](CU/5030/HW5-Q3.html)
    - [Question 4](CU/5030/HW5-Q4.html)
    - Data: [airpollution](CU/5030/airpollution.csv) (.csv)
    - Data: [rats](CU/5030/rats.csv) (.csv)
    - [Solutions](CU/5030/HW5_S.pdf)

##Labs
1. Lab 1 (Aug/27 - Aug/30)
    - [PDF](CU/5030/Lab1.pdf)
    - [RMarkdown](CU/5030/Lab1.Rmd) (.Rmd)
    - [Data](CU/5030/Faithful.csv) (.csv)
    - [Solution (PDF)](CU/5030/Lab1_S.pdf)
    - [Solution (RMarkdown)](CU/5030/Lab1_S.Rmd) (.Rmd)
2. Lab 2 (Sep/10 - Sep/13)
    - [PDF](CU/5030/Lab2.pdf)
    - [RMarkdown](CU/5030/Lab2.Rmd) (.Rmd)
    - [Data](CU/5030/hills.csv) (.csv)
3. Lab 3 (Sep/24- Sep/27)
    - [PDF](CU/5030/Lab3.pdf)
    - [RMarkdown](CU/5030/Lab3.Rmd) (.Rmd)
4. Lab 4 (Oct/1 - Oct/4)
    - [PDF](CU/5030/Lab4.pdf)
    - [RMarkdown](CU/5030/Lab4.Rmd) (.Rmd)
    - [Solution (PDF)](CU/5030/Lab4_S.pdf)
5. Lab 5 (Oct/29 - Nov/1)
    - [PDF](CU/5030/Lab5.pdf)
    - [RMarkdown](CU/5030/Lab5.Rmd) (.Rmd)
    - [Data](CU/5030/Grass.csv) (.csv)
    - [Solution (PDF)](CU/5030/Lab5_S.pdf)
    - [Solution (RMarkdown)](CU/5030/Lab5_S.Rmd) (.Rmd)
6. Lab 6 (Nov/12 - Nov/14)
    - [PDF](CU/5030/Lab6.pdf)
    - [RMarkdown](CU/5030/Lab6.Rmd) (.Rmd)
    - [Data](CU/5030/cherry.txt) (.txt)
    - [Data](CU/5030/golfballs.dat) (.dat)
    - [Solution (PDF)](CU/5030/Lab6_S.pdf)
    - [Solution (RMarkdown)](CU/5030/Lab6_S.Rmd) (.Rmd)
7. Lab 7 (Nov/26 - Nov/29)
    - [PDF](CU/5030/Lab7.pdf)
    - [RMarkdown](CU/5030/Lab7.Rmd) (.Rmd)
    - [Data](CU/5030/golfballs.dat) (.dat)
    - [Solution (PDF)](CU/5030/Lab7_S.pdf)

##Exams
- [Practice Midterm 1](CU/5030/Midterm1_Fall2017.pdf), Fall 2017 Midterm - 1
    - [Solution](CU/5030/Midterm1_Fall2017_S.pdf)
    - [Summary](CU/5030/Midterm1_Fall2017_Summary.html)
- [Practice Midterm 2](CU/5030/Midterm2_Fall2017.pdf), Fall 2017 Midterm - 2
    - [Solution](CU/5030/Midterm2_Fall2017_S.pdf)
- [Midterm Formulae](CU/5030/Formulae.pdf)
- [Midterm Solution](CU/5030/Midterm_S.pdf)
- [Practice Final](CU/5030/Final_Fall2017.pdf)
    - [Solution](CU/5030/Final_Fall2017_S.pdf)
- [Final Review](CU/5030/Final_Review.pdf)
    - [Solution](CU/5030/Final_Review_S.pdf)
- [Final Formulae](CU/5030/Formulae2.pdf)

---

#STSCI 5060 - Database Management and SAS High Performance Computing with DBMS
##Syllabus
- Fall 2018 Syllabus

##Lecture Slides
1. [Chapter 1 - Modern Database Management (MDBM)](CU/5060/Lec1.pdf)
2. [Chapter 2 - Modeling data in an organization (Basic E-R model)](CU/5060/Lec2.pdf)
3. [Chapter 3 - Enhanced E-R model](CU/5060/Lec3.pdf)
4. [Chapter 4 - Logical Database Design and the Relational Model](CU/5060/Lec4.pdf)
5. [Chapter 5 - Physical Database Design and Performance](CU/5060/Lec5.pdf)
6. [Chapter 6 - Introduction to SQL](CU/5060/Lec6.pdf)
7. [Chapter 7 - Advanced SQL](CU/5060/Lec7.pdf)
8. [PROC SQL 1](CU/5060/ProcSQL1.pdf)
9. [PROC SQL 2](CU/5060/ProcSQL2.pdf)
10. [PROC SQL 3](CU/5060/ProcSQL3.pdf)
11. [PROC SQL 4](CU/5060/ProcSQL4.pdf)
12. [PROC SQL 5](CU/5060/ProcSQL5.pdf)
13. [PROC SQL 6](CU/5060/ProcSQL6.pdf)
14. [PROC SQL 7](CU/5060/ProcSQL7.pdf)
15. [SAS HPC with DBMS_1](CU/5060/HPC1.pdf)
16. [SAS HPC with DBMS_2](CU/5060/HPC2.pdf)
17. [SAS HPC with DBMS_3](CU/5060/HPC3.pdf)
18. [SAS HPC with DBMS_4](CU/5060/HPC4.pdf)
19. [SAS HPC with DBMS_5](CU/5060/HPC5.pdf)

##Data Files
1. [customer](CU/5060/customer.sas7bdat) (.sas7bdat)
2. [employee_addresses](CU/5060/employee_addresses.sas7bdat) (.sas7bdat)
3. [employee_payroll](CU/5060/employee_payroll.sas7bdat) (.sas7bdat)
4. [employee_organization](CU/5060/employee_organization.sas7bdat) (.sas7bdat)
5. [flightattendants](CU/5060/flightattendants.sas7bdat) (.sas7bdat)
6. [flightdelays](CU/5060/flightdelays.sas7bdat) (.sas7bdat)
7. [flightschedule](CU/5060/flightschedule.sas7bdat) (.sas7bdat)
8. [frequentflyers](CU/5060/frequentflyers.sas7bdat) (.sas7bdat)
9. [mechanicslevel1](CU/5060/mechanicslevel1.sas7bdat) (.sas7bdat)
10. [mechanicslevel2](CU/5060/mechanicslevel2.sas7bdat) (.sas7bdat)
11. [mechanicslevel3](CU/5060/mechanicslevel3.sas7bdat) (.sas7bdat)
12. [order_fact](CU/5060/order_fact.sas7bdat) (.sas7bdat)
13. [payrollmaster](CU/5060/payrollmaster.sas7bdat) (.sas7bdat)
14. [price_list](CU/5060/price_list.sas7bdat) (.sas7bdat)
15. [sales](CU/5060/sales.sas7bdat) (.sas7bdat)
16. [salesstaff](CU/5060/salesstaff.sas7bdat) (.sas7bdat)
17. [staffmaster](CU/5060/staffmaster.sas7bdat) (.sas7bdat)
18. [supervisors](CU/5060/supervisors.sas7bdat) (.sas7bdat)
19. [Supervisors3](CU/5060/Supervisors3.sas7bdat) (.sas7bdat)

##Homeworks
1. [HW 1](CU/5060/HW1.pdf)
    - Due: Sep/26/2018 at 11:59PM
2. [HW 2](CU/5060/HW2.pdf)
    - Due: Oct/11/2018 at 11:59PM
3. [HW 3](CU/5060/HW3.pdf)
    - Due: Nov/28/2018 at 11:59PM
4. [HW 4](CU/5060/HW4.pdf)
    - Due: Dec/7/2018 at 11:59PM
    - Data: [Materials](CU/5060/Materials.sql) (.sql)
    - Data: [CREATEPVFC](CU/5060/CREATEPVFC.sql) (.sql)

##Labs
1. [Lab 1](CU/5060/Lab1.pdf)
    - Due: Oct/16/2018 at 11:59PM
    - [Lab 1 Summary](CU/5060/Lab1_Smy.html)
2. [Lab 2](CU/5060/Lab2.pdf)
    - Due: Oct/23/2018 at 11:59PM
    - Data: [CREATEPVFC](CU/5060/CREATEPVFC.sql) (.sql)
    - [Lab 2 Summary](CU/5060/Lab2_Smy.html)
3. [Lab 3](CU/5060/Lab3.pdf)
    - Due: Nov/12/2018 at 11:59PM
    - [Lab 3 Summary]((CU/5060/Lab3_Smy.html))

##Exams
- [Review](CU/5060/Review.html)

##Quizzes
1. [Quiz 1 with Solutions](CU/5060/Quiz1.pdf)
2. [Quiz 2 with Solutions](CU/5060/Quiz2.pdf)
3. [Quiz 3 with Solutions](CU/5060/Quiz3.pdf)

##Supplemental Materials
- [Oracle Database Datatypes](CU/5060/Sup1.pdf)
- [Oracle Schema Object Names and Qualifiers](CU/5060/Sup2.pdf)
- [Download and Install Oracle XE 11g](CU/5060/Sup3.pdf)

##Final Project
- [Instruction](CU/5060/FP.pdf)
- Data 1: [school_finance_2010](CU/5060/school_finance_2010.sas7bdat) (.sas7bdat)
- Data 2: [school_finance_2014](CU/5060/school_finance_2014.sas7bdat) (.sas7bdat)
- Description of Data 1 and Data 2: [Column Description](CU/5060/FP_CD.pdf)
- Data 3: [state_code](CU/5060/state_code.csv) (.csv)
- [Summary](CU/5060/FP_Summary.html)

---

#STSCI 5080 - Probability Models and Inference
##Syllabus
- [Fall 2018 Syllabus](CU/5080/Syllabus.pdf)

##Lecture Slides
1. [Lecture 1: Introduction](CU/5080/Lec1.pdf)
2. [Lecture 2: Probability and Conditional Probability](CU/5080/Lec2.pdf)
3. [Lecture 3: Independence and Random Variables](CU/5080/Lec3.pdf)
4. [Lecture 4: Discrete Random Variables](CU/5080/Lec4.pdf)
5. [Lecture 5: Continuous Random Variables](CU/5080/Lec5.pdf)
6. [Lecture 6: Continuous Random Variables (cont.)](CU/5080/Lec6.pdf)
7. [Lecture 7: Joint Distributions](CU/5080/Lec7.pdf)
8. [Lecture 8: Independence of RVs and Conditional Distributions](CU/5080/Lec8.pdf)
9. [Lecture 9: Generalizations and Functions of Random Vectors](CU/5080/Lec9.pdf)
10. [Lecture 10: Order Statistics and Expected Values](CU/5080/Lec10.pdf)
11. [Lecture 11: Expected Values](CU/5080/Lec11.pdf)
12. [Lecture 12: Expected Values (cont.)](CU/5080/Lec12.pdf)
13. [Lecture 13: Moment Generating Function](CU/5080/Lec13.pdf)
14. [Lecture 14: MGF and LLN](CU/5080/Lec14.pdf)
15. [Lecture 15: LLN and CLT](CU/5080/Lec15.pdf)
16. [Lecture 16: CLT, $\chi^2$ and $t$ Distributions](CU/5080/Lec16.pdf)
17. [Lecture 17: $\chi^2$ and $t$ Distributions](CU/5080/Lec17.pdf)
18. [Lecture 18: Sample Mean/Variance from Normal Population and Estimation](CU/5080/Lec18.pdf)
19. [Lecture 19: Maximal Likelihood Estimation](CU/5080/Lec19.pdf)
20. [Lecture 20: Maximal Likelihood Estimation (cont.)](CU/5080/Lec20.pdf)
21. [Lecture 21: MLE and Confidence Intervals](CU/5080/Lec21.pdf)
22. [Lecture 22: Confidence Intervals](CU/5080/Lec22.pdf)
23. [Lecture 23: Testing](CU/5080/Lec23.pdf)
24. [Lecture 24: Testing (cont.)](CU/5080/Lec24.pdf)
25. [Lecture 25: Review for the Final Exam](CU/5080/Lec25.pdf)

##Homeworks
1. [Homework 1](CU/5080/HW1.pdf)
    - [Solutions](CU/5080/HW1_S.pdf)
2. [Homework 2](CU/5080/HW2.pdf)
    - [Solutions](CU/5080/HW2_S.pdf)
3. [Homework 3](CU/5080/HW3.pdf)
    - [Solutions](CU/5080/HW3_S.pdf)
4. [Homework 4](CU/5080/HW4.pdf)
    - [Solutions](CU/5080/HW4_S.pdf)
5. [Homework 5](CU/5080/HW5.pdf)
    - [Solutions](CU/5080/HW5_S.pdf)
6. [Homework 6](CU/5080/HW6.pdf)
    - [Solutions](CU/5080/HW6_S.pdf)

##Discussions
1. [Discussion 1 with Solutions](CU/5080/Dis1.pdf)
2. [Discussion 2 with Solutions](CU/5080/Dis2.pdf)
3. [Discussion 3 with Solutions](CU/5080/Dis3.pdf)
4. [Discussion 4 with Solutions](CU/5080/Dis4.pdf)
5. [Discussion 5 with Solutions](CU/5080/Dis5.pdf)
6. [Discussion 6 with Solutions](CU/5080/Dis6.pdf)
7. [Discussion 7 with Solutions](CU/5080/Dis7.pdf)
8. [Discussion 8 with Solutions](CU/5080/Dis8.pdf)
9. [Discussion 9 with Solutions](CU/5080/Dis9.pdf)
10. [Discussion 10 with Solutions](CU/5080/Dis10.pdf)
11. [Discussion 11 with Solutions](CU/5080/Dis11.pdf)
12. [Discussion 12 with Solutions](CU/5080/Dis12.pdf)

##Supplementary Materials
1. [Some standard distributions](CU/5080/Sup1.pdf)
2. [Densities of order statistics](CU/5080/Sup2.pdf)
3. [More general definition of expectation](CU/5080/Sup3.pdf)
4. [CHF and MGF](CU/5080/Sup4.pdf)
5. [LeCam1986](CU/5080/Sup5.pdf)
6. [Portnoy2013](CU/5080/Sup6.pdf)
7. [Independence of sample mean and variance](CU/5080/Sup7.pdf)
8. [Brown_Cai_DasGupta_(2001,Stat.Sci.)](CU/5080/Sup8.pdf)
- [Formula](CU/5080/Formula.html)

##Practice Exams
1. [Practice Midterm 1](CU/5080/PM1.pdf)
    - [Solutions](CU/5080/PM1_S.pdf)
2. [Practice Midterm 2](CU/5080/PM2.pdf)
    - [Solutions](CU/5080/PM2_S.pdf)
3. [Practice Final](CU/5080/PF.pdf)
    - [Solutions](CU/5080/PF_S.pdf)

##Exams
1. [Midterm 1 with Solutions](CU/5080/M1_S.pdf)
2. [Midterm 2 with Solutions](CU/5080/M2_S.pdf)
    - [Formula Sheet](CU/5080/M2_Formula_Sheet.pdf)

---

<center>

Copyright © 2019 Harry Lu. All rights reserved.

</center>
