---
title: "Job Application Info"
output:
  html_document:
    toc: TRUE
    toc_float: 
      collapsed: FALSE
    toc_depth: 3
    number_sections: TRUE
---
<style>
h1 {font-size: 28px; color: black; font-weight: bold; text-align: left;}
h1.title {color: black; text-align: center;}
h2 {font-size: 20px; color: black; font-weight: normal; font-style: normal;}
h3 {font-size: 20px; color: black; font-weight: normal; font-style: italic;}
p {font-size: 16px; color: black;}
ol {font-size: 16px; color: black;}
ul {font-size: 16px; color: black;}
</style>

---

#Handshake
##Axtria
- 9.20 first interview

##Deloitte
###Deloitte Risk and Financial Advisory Associate - Customer Experience Measurement (Summer/Fall 2019)
> Applications close on October 4th at 7:55 pm

**Customer Experience Measurement Consultant**

Like to travel? Want an opportunity to use your excellent judgement, analytical abilities, and utilize your knowledge in the hospitality industry to serve as a quality consultant? At Deloitte, we provide enhanced brand and reputation risk management services to our clients. As a Customer Experience Measurement Consultant, which involves 100% field-based travel, you will use your expertise to lead quality-assurance examinations for brand assurance programs. You will be our clients’ eyes and ears, offering them information and feedback on their customers’ experience.

**Work you’ll do**

Motivated and ambitious, you will relish the opportunity to travel and work independently as you develop and deliver important summary presentations of evaluation findings to key client executives. Able to lead discussions with clients on business priorities, you will work closely with them to learn about their business, uncover their needs and help execute a program that helps deliver a more engaging, memorable customer experience.
 
**The team**

We help our clients protect their brands, deepen their customers’ advocacy, and strengthen their reputation through our end-to-end approach to Customer Experience Measurement. Our brand audit capabilities allows us to analyze consistency in numerous brands across different territories to provide property-level data and big picture insights to our clients. Our global capabilities position means we can help our clients minimize the risks to their brand and reputation.  Learn more about the team at Deloitte

**Qualifications**

Required:

- BA/BS degree in Hospitality or related fields
- Proficiency with all current word processing, spreadsheet, and presentation creation tools
- Experience working independently on multiple projects, while adhering to strict deadlines
- Excellent communication and analytical skills and be able to develop and present examination results in a friendly, empathetic and helpful manner
- Demonstrated ability to exercise discretion and independent judgment by using industry knowledge and fully comprehending clients’ business models and needs 
- Must be prepared to travel extensively throughout any region or country required by the client (100%, 52 weeks per year)
- Ability to obtain valid driver's license
- Must reside in close proximity to a major international airport ( < 50 Miles)
Preferred
- Strong academic track record (minimum GPA of 3.2)
- Internship or minimum one year hospitality, tourism, retail or other customer service experience

**How you’ll grow**

At Deloitte, we believe in professional development and helping our people grow. We offer learning opportunities to help you sharpen your skills in addition to hands-on experience in the global, fast-changing business world. We support the development of leadership and technical skills through leading-edge learning development solutions. When you join, you’ll participate in Welcome to Deloitte, a two-day orientation followed by the New Hire Seminar where you will be introduced to many of the fundamental aspects of your upcoming journey.

**Benefits**

At Deloitte, we know that great people make a great organization. We value our people and offer employees a broad range of benefits.

**Deloitte’s culture**

Our positive and supportive culture encourages our people to do their best work every day. We celebrate individuals by recognizing their uniqueness and offering them the flexibility to make daily choices that can help them to be healthy, centered, confident, and aware. We offer well-being programs and are continuously looking for new ways to maintain a culture where our people excel and lead healthy, happy lives. Learn more about Life at Deloitte.

**Corporate citizenship**

Deloitte is led by a purpose: to make an impact that matters. This purpose defines who we are and extends to relationships with our clients, our people, and our communities. We believe that business has the power to inspire and transform. We focus on education, giving, skill-based volunteerism, and leadership to help drive positive social impact in our communities. Learn more about Deloitte’s impact on the world.

**Recruiter tips**

We want job seekers exploring opportunities at Deloitte to feel prepared and confident. To help you with your interview, we suggest that you do your research: know some background about the organization and the business area you’re applying to. We also suggest that you brush up on your interviewing skills and practice discussing your experience and job history with a family member, friend, or mentor. Check out recruiting tips from Deloitte professionals.

**How to apply**

1. Handshake application: When applying through Handshake, you will need to submit your cover letter, resume, and unofficial transcripts. Please submit your resume and unofficial transcripts on both the campus career center as well as on the Deloitte career site. You may use the following naming convention when naming your documents First,
2. Deloitte website: In addition to applying through Handshake, you are also required to apply through the Deloitte website for legal purposes. Below are the steps to apply for this position: 
3. Go to https://jobs2.deloitte.com 
4. Enter the keyword “S19NATEF20JULTB-LRA” to search for the job posting.
5. Complete profile.
d. Once you've completed your candidate profile on our website you will be prompted to complete an online application several days after. Please complete that upon receipt.
e. Additionally please complete the following survey, http://talent.force.com/event/checkin?eid=a0T1W0000063ygKUAQ&SC=Multi+School+Event

As used in this document, “Deloitte Risk and Financial Advisory” means Deloitte & Touche LLP, which provides audit and risk advisory services; Deloitte Financial Advisory Services LLP, which provides forensic, dispute, and other consulting services; and its affiliate, Deloitte Transactions and Business Analytics LLP, which provides a wide range of advisory and analytics services. These entities are separate subsidiaries of Deloitte LLP. Please see www.deloitte.com/us/about for a detailed description of our legal structure. Certain services may not be available to attest clients under the rules and regulations of public accounting.

All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age, disability or protected veteran status, or any other legally protected basis, in accordance with applicable law.

##McKinsey & Company
###Data Scientist
> Applications close on October 7th at 11:59 pm

**Who You'll Work With**

You will work with an Advanced Analytics team in one of our global offices. Blending strategic thinking with hands-on practicality, our teams of consultants and experts work to develop and implement complex analytics strategies that solve our clients' most critical problems.

Our teams are made up of analysts, mathematicians, data scientists, designers, software engineers, product managers, client development managers and general managers with a base of expertise in a function or industry. Data Scientists are staffed on engagements or product teams and are expected to leverage expertise to solve some of the most pressing and complex issues at clients.

**What You'll Do**

You will perform statistical data analyses, data mining and optimizations using multiple tools and techniques to get insights from large complex data sets.

In this role you will conduct hands-on rigorous quantitative analysis, including getting the data, cleaning it (when necessary / relevant), and exploring it for accuracy. You'll deploy statistical modeling and optimization techniques most suited for the business problem (using R, Python, SQL, and/or other relevant tools). With support, you'll advise client teams on analytic methodologies and approaches to address their specific needs, including discussing data collection, architecture, associated costs and trade-offs, and recommendations.

You'll interpret outputs of statistical models and results to translate input from quantitative analyses into specific and actionable business recommendations and implications. This includes providing detailed documentation of modeling techniques, methodologies, assumptions made and process steps.

You'll manage delivery of analytical solutions to client via written and verbal presentations, including capability building as appropriate. You may advance McKinsey’s overall knowledge base by providing analytical rigor and problem solving to our proprietary knowledge investments.

You'll begin to own an analytics work stream, manage respective tasks and client project team members/experts, while building client relationships. You'll support analytics recruiting efforts (e.g., attends recruiting events, participates in WebExes, etc.)

**Qualifications**

- University student in their final year in a STEM related field (Ops Research, Statistics, Applied Math, Engineering, Business Analytics); expected graduation date of December 2018 or May 2019. Or, currently completing your first year in a non-business, 2-year masters program and have less than 2 years of work experience
- Deep understanding of statistical and predictive modeling concepts, machine-learning approaches, clustering and classification techniques, and recommendation and optimization algorithms
- Experience in one or more programming languages (R, Python, C++, etc.)
- Ability to easily understand the complex algorithm and logic to process data
- Experience working with a large volume of data with ability to solve performance issues
- Practitioner of statistical data quality procedures or test driven approach for quality assurance
- Basic business intuition and clear expertise in analyses with the ability to describe analytic processes, including when and why specific approaches are favored
- Excellent communication and presentation skills with an ability to visualize and report insights creatively in variety of formats to various stakeholders
- Ability to deliver in deadline-driven environment
- Team player with a passion for coaching colleagues and clients
- Willingness to travel up to 80%

In order to be properly considered, please apply direct to the role: https://www.mckinsey.com/careers/search-jobs/jobs/data-scientist-university-students-2736

##IBM
###Entry-Level Data Scientist - 178769BR - (Fall 2018)
> Applications close on November 30th at 6:55 pm

At IBM we have an amazing opportunity to transform the world with cognitive technology. By using the vast amounts of information available today to identify new patterns and make new discoveries, we are helping cities become smarter, hospitals transform patient care, financial institutions minimize risk, and pharmaceuticals find cures for rare diseases. Join the forward-thinking teams at IBM solving some of the world’s most complex problems – there is no better place to grow your career!

Entry-Level Data Scientists extract knowledge or insights from structured or unstructured data. They draw upon the practice of data analysis, using predictive analytics, data mining, pattern recognition, data modeling, machine learning and various statistical methods in order to solve large scale optimization problems and to understand the meaning behind vast data sets

Entry-Level Data Scientists are in demand across IBM's growth areas. You'll be matched and deployed to a team in a strategic business, based on your offered location and fit.

**What You’ll Do:**

- You will implement and validate predictive models, and create and maintain statistical models with a focus on big data.
- You’ll communicate with internal and external clients to understand business needs and provide analytical solutions.
- You will use statistical concepts such as regression, time series, mixed model, Bayesian methods, clustering, etc., to analyze data and provide insights.
- You’ll work in an Agile, collaborative environment, partnering with other scientists, engineers, and database administrators of all backgrounds and disciplines to bring analytical rigor and statistical methods to the challenges of predicting behaviors.

**Who You Are:**

- You are great at solving problems, debugging, troubleshooting, and designing & implementing solutions to complex technical issues.
- You thrive on teamwork and have excellent verbal and written communication skills.
- You have strong technical and analytical abilities, a knack for driving impact and growth, and some experience with programming/scripting in a language such as Java or Python.
- You have a basic understanding of statistical programming in a language such as R, SAS, or Python.
- You have an interest in, understanding of, or experience with Design Thinking Methodology
- You have an interest in, understanding of, or experience with Agile development methodology

**Required Technical and Professional Expertise**

Must have basic knowledge of statistical concepts such as regression, time series, mixed model, Bayesian methods, clustering, etc., to analyze data and provide insights.

**Preferred Tech and Prof Experience**

Some work experience using statistical concepts such as regression, time series, mixed model, Bayesian methods, clustering, etc., to analyze data and provide insights.

##Raymond James Financial
###2019 Summer Internship Development Program- Carillon Tower Advisers-Data Insights & Marketing Analytics Intern
> Applications close on January 31st at 11:59 pm

**Department Description:**

Carillon Tower Advisers is a global asset-management company that combines the exceptional insight and agility of individual investment teams with the strength and stability of a full-service firm. We believe providing a lineup of institutional-class portfolio managers — spanning a wide range of disciplines and investing vehicles — is the best way to help investors seek their long-term financial goals.

**Job Summary:**

Under general supervision, uses skills gained through training and experience to assist with specific projects within an assigned functional area for a specified period of time. Follows established procedures to perform tasks and receives general guidance and direction to perform other work with substantial variety and varied complexity. Some judgment is required to adapt procedures, processes and techniques to apply to more complex assignments. Resolves routine questions and problems and refers more complex issues to a higher level. Routine contact with internal and external customers may be required to exchange basic information.

**Essential Duties and Responsibilities:**

- Specified projects and varied assignments.
- Operates standard office equipment and uses required software applications.
- Assists in conducting market research projects and analyzing and reporting results.
- Gathers information and data on competitors' products, services and marketing techniques.
- Assists in reviewing and analyzing the service/product posture of assigned functional area.
- Assists in maintaining a market intelligence database. Maintains records and files on research projects.
- Performs other duties and responsibilities as assigned.

**Knowledge, Skills, and Abilities:**

**Knowledge of:**

- Fundamental concepts, practices and procedures of a professional office environment.
- Basic concepts, principles and practices of an assigned business unit.

**Skill in:**

- Operating standard office equipments and using, or have the ability to learn, required software applications.

**Ability to:**

- Organize and prioritize multiple tasks and meet deadlines.
- Communicate effectively, both orally and in writing.
- Work independently as well as collaboratively within a team environment.
- Provide a high level of customer service.
- Establish and maintain effective working relationships

**Educational/Previous Experience Requirements:**

- Any equivalent combination of experience, education, and/or training approved by Human Resources.
- Rising Junior or Senior currently enrolled in an accredited university.
- MIS, Data Insights, Marketing, or Finance Majors preferred.
- 3.0 GPA minimum preferred.

**Licenses/Certifications:** None Required.

##Indus Valley Partners
###Junior Business Analyst
> Applications close on October 4th at 11:59 pm

Indus Valley Partners (IVP) is currently looking for entry-level Junior Business Analysts to join our team. This is an exciting opportunity to work with an established technology solutions and consultancy in the alternative investment financial services industry.

Our Junior Business Analysts (JBA) are involved in all aspects of the project lifecycle and work hands on with client stakeholders during the consulting, design, and production stages of each engagement.

**Responsibilities**

- Serve as the “liaison” by gathering and analyzing business requirements from client and user groups and then communicating these requirements with development and software engineers.
- Learn and develop understanding of IVP solutions and where they fit in the client workflow
- Hone client skills by gathering requirements from client discussions, interviews, testing, analysis, and other forms of requirements discovery
- Document and present requirements effectively
- Work closely in coordination with development teams to implement and develop technological solutions that satisfy client needs
- Iterate on designs based on user feedback and UAT testing until solutions effectively meet end user requirements
- Lead the implementation cycle, drive decisions, track and document issues, and assist in managing and meeting tight deadlines while working with cross-functional teams to see projects from concept to completion
- Ability to discuss, manage, document, and design decisions to varied audiences

**Qualifications**

- A demonstrable interest in both finance and technology with a high degree of computer literacy
- A self-starting, entrepreneurial attitude, willing to take initiative and work through all obstacles to accomplish tasks
- Outstanding communication is a must – presentation, documentation, and interpersonal skills are critical for the role
- Strong analytical and quantitative problem solving ability, able to think, and act decisively
- Ability to thrive when working with multiple groups in a variety of settings with ability to listen, articulate positions, advocate designs, and affect change
- Bachelor’s degree with strong academic background
- Must be open to travel
- Understanding of alternative investments and the financial services industry – preferred
- Proficient with Microsoft Excel, Word, PowerPoint (databases and knowledge of SQL is also preferred)
Indus Valley Partners offers a competitive salary and benefits package.

**About Indus Valley Partners (IVP)**

IVP is a technology solutions and consultancy focused on the alternative asset management industry. We assist over 135 alternate asset managers including 25 of the top 50 global hedge funds, and everyday our products and services cover over $1 Trillion in assets with our client base representing over a quarter of all current hedge fund assets under management. We help fund managers generate alpha by analyzing their portfolio data to generate actionable insights, institutionalizing their fund platforms and reducing their non-investment risks.

Founded in 2000, we currently have 500+ professionals, working across 4 time-zones with over 16 years of in-depth domain expertise and insight. To learn more please visit our website at http://www.indusvalleypartners.com.

##Procter & Gamble (P&G)
###Business Analytics Manager
> Applications close on December 21st at 11:59 pm

Are you an effective communicator, self-motivated, and able to drive insights into actions that improve business results? You’ll need to mine terabytes of data, derive actionable insights, and translate complex results or algorithms into simple conclusions that will empower others. You are the primary evangelist for the power of predictive analysis and developing business cases to illustrate the “step-change” in decision-making. Business knowledge, interpersonal, and communication skills are therefore a need to thrive in a multi-functional leadership team.

We are currently looking for Managers for two roles:

**Data Analyst**

- You will deliver analytic insights in several business domains (consumer, customer, digital, etc…). With a combination of analytical expertise, data and system knowledge and business acumen, you’ll answer and anticipate critical business questions and opportunities and deliver critical insights. You’ll use data visualization (Spotfire), and analytic tools (R, SAS, JMP, Python, etc) to grasp the business building insights in our mountains of data.

**Trade Spend Analyst**

- You will optimize store promotion plans using multiple data sources and analytical models. You’ll perform financial/marketing/promotion analytics and make recommendations back to key partners. You should understand when, how, and where to directly use, to adjust, or to estimate Price & Promotion data. You’ll leverage data visualization (KNIME, RapidMiner, Tableau, Spotfire, etc.), and analytic tools (R, Python, C++, Java, Scala, etc.) to grasp the business building insights in our mountains of data.

**OUR IT**

IT is where business, innovation and technology integrate to build a competitive advantage for us. Our mission is clear -- we deliver IT to help win with consumers. Are you a diverse business leader who applies IT mastery to deliver groundbreaking, technology-driven business models and capabilities? Whether your role is to build an IT innovation strategy for a business, protect our critical information systems and assets, or lead a strategic supplier in our state of the art shared services organization, your technical mastery will be recognized and rewarded. Your real passion for the industry will be further nurtured by our culture of continued learning and growth. Your career in IT builds change in leadership and influence skills, breadth of experience across multiple businesses, and depth of expertise in areas like Application & Integration, Infrastructure, Data & Analytics, and Security & Risk.

**WHAT ABOUT P&G?**

P&G serves consumers around the world with one of the strongest portfolios of trusted, quality, leadership brands, including Always®, Ambi Pur®, Ariel®, Bounty®, Charmin®, Crest®, Dawn®, Downy®, Fairy®, Febreze®, Gain®, Gillette®, Head & Shoulders®, Lenor®, Olay®, Oral-B®, Pampers®, Pantene®, SK-II®, Tide®, Vicks®, and Whisper®. The P&G community includes operations in approximately 70 countries worldwide.
 
All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, national origin, protected veteran status, disability status, age, sexual orientation, gender identity and expression, marital status, citizenship, HIV/AIDS status or any other legally protected factor.
 
Immigration sponsorship is not available for this position. Applicants for U.S. based positions are generally required to be eligible to work in the U.S. without the need for current or future sponsorship. Except in rare situations based on Procter & Gamble's sole discretion. Procter & Gamble does not sponsor candidates for permanent residency. Any exceptions would be based on the Company's specific business needs at the time and place of recruitment as well as the particular qualifications of the individual.
 
Procter & Gamble participates in e-verify as required by law.
 
Qualified individuals will not be disadvantaged based on being unemployed.

###Associate Information Technology Manager
> Applications close on December 22nd at 12:55 am

**General Description:**

As an entry-management level Associate IT Manager in P&G Information Technology function, you will be assigned in a specific business domain (e.g. Digital Marketing, Supply Chain, Sales, IT Infrastructure etc.), partnering with multi-functional & vendor resources to resolve specific business problems by applying information technology. You will be leading the effort of business process transformation, project management and application lifecycle management.

**Key Responsibilities:**

**Business Solution Delivery**

Lead business transformation and solution delivery that supports well-defined business objectives by leveraging on technology. Effectively influence business leadership alignment on the transformation.

- Understand and analyze existing business processes.
- Understands business requirements and effectively collaborate with multi-function team to translate business needs and process into technical requirements and specifications.
- Be accountable for the value /success of the final solution as proposed in the business case

**Project Management**

- Lead a project team with multi-function and vendor resources. Be accountable for project success by strong project management skill, e.g. scope, budget, time and quality management.
- Own project success criteria and business value realization.
- Manage the delivery of requirements documents, use-case documentation, prototypical user experiences, test plans, and rollout communications

**Application Management & Enterprise Architecture**

- Provide technical and thought leadership on system architecture, application integration and development initiatives. Actively participates in the development of technical architecture for assigned systems and projects
- Connect externally, evaluate new technologies and identify the benefit business case for using new technologies.
- Manage complex software development and integration technology projects in a fast paced, constantly changing dynamic environment.
- Manage IT vendor partners to ensure timely, quality and cost effective delivery of solution and services.

**Qualifications**

- Strong team leadership and ability to collaborate effectively with both internal and external resources at all levels of the organization (working effectively with peers, vendor-partners, senior management, multi-functional team both internally and externally).
- Strong problem solving skills, technical/analytical skills and ability to multi-task and balance different sets of priorities.
- Ability to engage in senior level technology decision discussions related to business value and the end-to-end information technology lifecycle.
- Demonstrated competency/mastery in one or more fields of IT technology (ERP, Application Management, Database Engineering, IT Infrastructure, Cyber Security, CRM, Mobility and others) and have demonstrated learning agility to learn and apply the latest technologies.
- Proficient written and oral Mandarin and English communication skills are required in this global environment

##Wayfair
###Business Analyst - Winter 2018 or Summer 2019 Full-Time Start
> Applications close on December 1st at 11:59 pm

Wayfair believes everyone should live in a home they love. Through technology and innovation, Wayfair makes it possible for customers to quickly and easily find exactly what they want from furnishings, décor, home improvement, housewares and more.

We are always looking for imaginative, analytical, and adaptable people to join our home team. You’ll find a dynamic atmosphere where learning and growth opportunities are abundant, and hard work and results are rewarded. We’re a diverse community of innovators, risk-takers, and trailblazers who know that our unique perspectives make us stronger, smarter, and well-positioned for success. Every voice, every perspective matters. We are proud to be an equal opportunity employer.

At Wayfair, you can explore your potential outside of the classroom and take the lead on high-impact projects. You’ll find autonomy, mentorship, and development opportunities in an open and collaborative environment. If you’re looking for a challenging and fulfilling career, make yourself at home.

Wayfair generated $5.7 billion in net revenue for the twelve months ended June 30, 2018. Headquartered in Boston, Massachusetts with operations throughout North America and Europe, the company employs more than 9,700 people.

**THE OPPORTUNITY**

Wayfair is seeking analytical, entrepreneurial, and action-oriented candidates for full-time Business Analyst roles with start dates in Winter 2018 or Summer 2019. Analysts will directly impact Wayfair’s growth strategy and competitive positioning by leveraging data-driven analyses and innovative approaches to drive results for internal and external business partners. Successful Analysts are quantitatively-oriented, endlessly curious, and thrive in fast-paced and collaborative environments. This is an ideal launching point for candidates who are interested in entering the tech space and joining a high-growth company that develops and invests in future leaders.

Wayfair hires Business Analysts into eight core business functions that fall under the categories of Business and Strategic Analysis, Customer Growth and Product, Operations and Analytics, and Talent & Finance. Function placement is determined through the application and interview process and is dependent on a combination of interest, skills and experience, and growth potential. **When applying, please indicate your top choices for functional areas of interest (in order of preference). If we notice a stronger alignment for a team other than those indicated in the application, we will also consider you for that opportunity.**

**Functional areas and potential team placements include:**

**1. BUSINESS AND STRATEGIC ANALYSIS**

**1.1 Competitive Intelligence**

Competitive Intelligence focuses on optimizing Wayfair’s strategic positioning within its rapidly evolving competitive landscape. This cross-functional and entrepreneurial team uses Big Data and cutting edge advanced analytics capabilities to build products and identify insights that impact every major business function at the company; the unique, external market perspective brought by this team complements our robust internal data asset to Wayfair to make more informed decisions. Past Analyst projects have included: developing first-ever dynamic visualizations that enable category managers to optimize our product selection, creating products that track competitor movements and assess relative strategic importance over time, and collaborating with our Data Science team to build multiple machine-learning algorithms to match competitor products.

**1.2 Strategy & Profitability**

At its core, the Strategy and Profitability team is focused on steering growth strategy and billion-dollar P&L management across Wayfair’s product verticals by leveraging highly quantitative business analytics and cutting-edge data science techniques. This tight-knit team has a big appetite for bold ideas, a strong bias for action, and provides a distinct opportunity to drive high impact decisions with unique executive-level visibility. Analysts directly control Wayfair’s dynamic pricing and product sorting algorithms to manage the delicate tradeoff between short and long term profitability, while working cross-functionally to affect product selection, merchandising, operations, and marketing initiatives. Analysts leverage unique, proprietary, and massive datasets coupled with a constant flow of experimentation on consumer response to answer thorny strategic questions that guide go-to-market strategy. Strong candidates will be highly entrepreneurial, excited to analyze big data, and eager to engage as a thought leader while collaborating with a highly cross-functional group of business partners.

**2. CUSTOMER GROWTH AND PRODUCT**

**2.1 Customer Growth**

The Customer Growth team fuels growth by introducing new customers to Wayfair and driving engagement from our loyal customer base. We drive profitable top line revenue by investing our marketing dollars where they will provide the greatest return for the business and leveraging our understanding of the customer to impact the overall business strategy. We work cross-functionally with Engineering, Product Management, and Data Science teams to build our own cutting-edge ad tech platforms and partner closely with leading companies in the tech space such as Google and Facebook to alpha-test new advertising products and influence their product innovations. As an Analyst, you’ll be assigned to a specific channel (e.g. Search, Display, Email, Social Media, TV/Online Video, etc.) and own it end-to-end. You’ll be tasked with managing a multimillion dollar budget, helping drive ad tech development, and devising new testing strategies to grow the business. Applying a test-and-learn approach, your day-to-day decisions will have a direct and measurable impact on the business.

**2.2 Product Management**

Operations Product Innovation (OPI) is the Product Management team for Wayfair Operations. We lead the design and delivery of technology solutions for the customer experience, supplier engagement, delivery network optimization, and warehouse logistics. By partnering with operations, analytics, and engineering we transform data into insights and deliver continuous value to our customers. You will be empowered to drive the end-to-end product management for technically complex strategies from ideation to implementation. This includes problem/opportunity identification, synthesizing project requirements, data analysis to inform prioritization, and iterative development. Strong candidates will possess a bias for action, have an insatiable curiosity when solving unique problems, and effectively collaborate cross-functionally.


**3. OPERATIONS AND ANALYTICS**

**3.1 Supply Chain & Logistics**

Wayfair’s Supply Chain organization is revolutionizing the customer experience through the development of a proprietary logistics network and optimization platform that manages inventory from the overseas factory to the customer’s front door. Teams include Inventory Planning Strategy, Product Performance, Product Availability, Small and Large Parcel Strategy, Custom Supply Chain, Global Delivery, and more. Strong candidate will possess strong business acumen, analytical horsepower, and an appetite for solving challenging business problems. This is a unique opportunity to help build another competitive advantage for Wayfair.

**3.2 Supply Chain Analytics**

Supply Chain Analytics sits at the center of Wayfair Logistics, using data and analytics to support strategic and operational decisions such as warehouse location optimization, network and transportation design, forecasting and capacity planning, and processes to reduce damages – all of which are critical to propelling Wayfair’s exponential business growth. This is a top investment area for Wayfair, a CEO focus, and a key strategic differentiator for the business. Team members are exposed to highly cross-functional projects and challenged in innovative thinking, business problem-solving, quantitative data analysis, predictive modeling, and analytic process development. Analysts will be rewarded with not just analytical, but well-rounded business experience to pursue a variety of career paths.

**4. TALENT & FINANCE**

**4.1 People Analytics**

The Talent team believes that our people are Wayfair’s greatest asset and biggest differentiator. As Wayfair grows, so too does the need to ensure our talent strategy and approach is best in class. The People Analytics team drives Wayfair’s strategy to attract, retain, and develop world class talent. Analysts will take a data driven approach to human capital and work closely with Wayfair leadership to improve the employee experience through data and raise the bar on organizational effectiveness. Strong candidates will demonstrate sound business acumen, analytical skills, and high EQ. 

**4.2 Finance**

The Finance team sits at the intersection of Wayfair's brands and functional teams and has unique access to the operation and decision-making of the entire business. Analysts will join a Finance Rotational Program that provides the opportunity to gain experience across several of Wayfair's Strategic Finance teams. Throughout the course of the program, new hires will be embedded on several of Wayfair’s most impactful teams and work alongside senior leadership to drive insights for our growing business. Participating teams include Investor Relations, FP&A, Operational Finance, B2B Operational Finance, Real Estate and Procurement, among others. Strong candidates will possess excellent organizational, quantitative, and analytical skills with a strong aptitude for problem-solving and the ability to make numbers come alive by clearly conveying complex information in a way that supports decision-making.

**Qualifications:**

- BA/BS or Master’s degree earned by date of hire; preferably with strong quantitative focus
- Strong academic record
- Demonstrated leadership through campus involvement; former internship or work experience is a plus
- Exceptional problem-solving and analytical skills
- Creative and innovative approach to solving problems; a desire to make processes better
- Entrepreneurial spirit and a demonstrated self-starter mentality
- Ability to juggle multiple projects simultaneously
- Interest in working hard and being challenged in a fast-paced environment
- Strong written and verbal communication skills
- Positive, people-oriented, and enthusiastic attitude
- Proficient with MS Excel
- Experience with programming language (SQL or R) is a plus

##GE
###3150423 - Digital Technology Leadership Program (DTLP)
> Applications close on October 2nd at 11:55 pm

**Title: 3150423 - Digital Technology Leadership Program (DTLP)**

**Business:** GE Corporate

**Function:** Digital Technology

**Location: Various US Locations**

**About Us:**

GE is the world's Digital Industrial Company, transforming industry with software-defined machines and solutions that are connected, responsive and predictive. Through our people, leadership development, services, technology and scale, GE delivers better outcomes for global customers by speaking the language of industry.

**Role Summary/Purpose:**

The Digital Technology Leadership Program (DTLP) offers those with a passion to grow their leadership, business acumen, and technical skills while building a career with unlimited potential. Program members lead by doing, gaining real-world experience by working on important, challenging projects alongside some of the brightest technical minds in the world.

**Qualifications/Requirements:**

- A Bachelor’s Degree in Computer Science, CIS, Computer Engineering, IT Security, ITM, Informatics, Information Science, Information Systems, Information Technology, MIS, Security and Risk Analysis or relevant STEM majors with experience in Software or IT experience 
- Minimum cumulative 3.0/4.0 GPA or equivalent 
- Graduating by May/June 2019 

**Eligibility Requirements:**

- Must be geographically mobile as requested by the business
- Legal authorization to work in the U.S. is required. We will not sponsor individuals for employment visas, now or in the future, for this job

**To be considered for an interview you MUST ALSO apply through our website: www.ge.com/careers and search for Job# 3150423**

**Desired Characteristics:**

- Strong analytical skills.
- Must be flexible and able to navigate an ever-changing work environment
- A strong commitment to a career in technology with a passion and aptitude for both software and information technology
- Up-to-date with current industry standards, trending software, and information technology development tools  
- Prior intern, co-op, or research experience in IT, software, or relevant area  
- Solves technical challenges through regular application of common design patterns, and ability to identify appropriate patterns for use in problem solving
- Ability to understand coding standards that meet and deliver desired functionality using the technology selected for the project  
- Strong customer focus, ability to understand the value proposition for the customer, and commitment to deliver the best value proposition  
- Able to engage positively across multiple departments to establish clarity, vision, and mutual trust to achieve business goals 
- Demonstrated program/project management skills working on and leading teams
- Leadership experience inside and/or outside the classroom
- Excellent written and verbal communication skills; ability to articulate technical problems in clear and simple terms
- Contributes to creative solutions and challenges the status quo
- Proactively learns new tools and identifies opportunities for improvement and promotes their adoption 
 
**Essential Responsibilities:**

- Full-time, two-year leadership development program where members work within a GE business alongside experts in various locations 
- Four, six-month rotational assignments within your specific business covering diverse projects in Digital Engineering, Data Analytics & Operations, Technical Product Management, and more. 
- Global classroom experience and virtual coursework focused on technical training, leadership, and business acumen  
- Over the course of the program, you’ll receive a broad set of diverse assignments spanning product management, data analytics, IT operations, software development, and more.

GE offers a great work environment, professional development, challenging careers, and competitive compensation. GE is an Equal Opportunity Employer. Employment decisions are made without regard to race, color, religion, national or ethnic origin, sex, sexual orientation, gender identity or expression, age, disability, protected veteran status or other characteristics protected by law.

---

#Others
##EY

##Deloitte
###Business Technology Analyst (BTA)



##Amazon


##IBM


##IBM China