---
title: "2019 Summer #1"
output:
  html_document:
    toc: FALSE
    toc_float:
      collapsed: FALSE
    toc_depth: 2
---

<style>
h1 {font-size: 28px; color: black; font-weight: bold; text-align: center;}
h1.title {color: black; text-align: center;}
h2 {font-size: 20px; color: black; font-weight: bold; font-style: italic;}
p {font-size: 16px; color: black;}
ol {font-size: 16px; color: black;}
ul {font-size: 16px; color: black;}
table {border: 1px solid black; border-collapse: collapse; margin-top: 10px; margin-bottom: 10px;}
td {border: 1px solid black; width: 200px; height: 50px; text-align: center; font-size: 16px; color: black;}

td.diagonalRising {
	background: linear-gradient(to right bottom,
	  Snow 0%,
	  Snow 49.9%,
	  Black 50%,
	  Black 51%,
	  Snow 51.1%,
	  Snow 100%);
}
td.pending {background-color: LightSalmon;}
td.updated {background-color: MediumSpringGreen;}
</style>

---

# Time Table
## May/2019
<table>
<tr>
  <td>**Mon**</td>
  <td>**Tue**</td>
  <td>**Wed**</td>
  <td>**Thu**</td>
  <td>**Fri**</td>
  <td>**Sat**</td>
  <td>**Sun**</td>
</tr>
<tr>
  <td></td>
  <td class="pending">22nd  
    [Class 1](LO/Algorithm_Class_1.html)</td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td class="updated">26th  
    [Practice 1](LO/Algorithm_Class_2.html)</td>
</tr>
<tr>
  <td class="updated">27th  
    [Class 2](LO/Algorithm_Class_3.html)</td>
  <td></td>
  <td class="updated">29th  
    [Practice 2](LO/Algorithm_Class_4.html)</td>
  <td></td>
  <td class="updated">31st  
    [Practice 3](LO/Algorithm_Class_5.html)</td>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
</tr>
</table>

- Class 1: Binary Search [Link](LO/Algorithm_Class_1.html) (pending)
    - Practice 1 [Link](LO/Algorithm_Class_2.html)
- Class 2: Recursion I and Sorting Algorithms [Link](LO/Algorithm_Class_3.html)
    - Practice 2 [Link](LO/Algorithm_Class_4.html)
    - Practice 3 [Link](LO/Algorithm_Class_5.html)

## June/2019
<table>
<tr>
  <td>**Mon**</td>
  <td>**Tue**</td>
  <td>**Wed**</td>
  <td>**Thu**</td>
  <td>**Fri**</td>
  <td>**Sat**</td>
  <td>**Sun**</td>
</tr>
<tr>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
  <td class="updated">1st  
    [Class 3](LO/Algorithm_Class_6.html)</td>
  <td class="updated">2nd  
    [Practice 4](LO/Algorithm_Class_7.html)</td>
</tr>
<tr>
  <td class="updated">3rd  
    [Class 4](LO/Algorithm_Class_8.html)</td>
  <td></td>
  <td class="updated">5th  
    [Practice 5](LO/Algorithm_Class_9.html)</td>
  <td></td>
  <td class="updated">7th  
    [Class 5](LO/Algorithm_Class_10.html)</td>
  <td class="updated">8th  
    [Practice 6](LO/Algorithm_Class_11.html)</td>
  <td class="updated">9th  
    [Practice 7](LO/Algorithm_Class_12.html)</td>
</tr>
<tr>
  <td class="updated">10th  
    [Practice 8](LO/Algorithm_Class_13.html)</td>
  <td></td>
  <td class="updated">12th  
    [Class 6](LO/Algorithm_Class_14.html)</td>
  <td></td>
  <td class="updated">14th  
    [Practice 9](LO/Algorithm_Class_15.html)</td>
  <td class="updated">15th  
    [Class 7](LO/Algorithm_Class_16.html)</td>
  <td class="updated">16th  
    [Practice 10](LO/Algorithm_Class_17.html)</td>
</tr>
<tr>
  <td class="updated">17th  
    [Practice 11](LO/Algorithm_Class_18.html)</td>
  <td></td>
  <td class="updated">19th  
    [Practice 12](LO/Algorithm_Class_19.html)</td>
  <td></td>
  <td class="pending">21st  
    [Class 8](LO/Algorithm_Class_20.html)</td>
  <td class="pending">22nd  
    [Class 9](LO/Algorithm_Class_21.html)</td>
  <td class="updated">23rd  
    [Practice 13](LO/Algorithm_Class_22.html)</td>
</tr>
<tr>
  <td class="pending">24th  
    [Practice 14](LO/Algorithm_Class_23.html)</td>
  <td></td>
  <td class="pending">26th   
    [Class 10](LO/Algorithm_Class_24.html)</td>
  <td></td>
  <td class="pending">28th  
    [Practice 15](LO/Algorithm_Class_25.html)</td>
  <td>29th  
    [Class 11](LO/Algorithm_Class_26.html)</td>
  <td class="pending">30th  
    [Practice 16](LO/Algorithm_Class_27.html)</td>
</tr>
</table>

- Class 3: Linked List [Link](LO/Algorithm_Class_6.html)
    - Practice 4 [Link](LO/Algorithm_Class_7.html)
- Class 4: Queue and Stack [Link](LO/Algorithm_Class_8.html)
    - Practice 5 [Link](LO/Algorithm_Class_9.html)
- Class 5: Binary Tree & Binary Search Tree [Link](LO/Algorithm_Class_10.html)
    - Practice 6 [Link](LO/Algorithm_Class_11.html)
    - Practice 7 [Link](LO/Algorithm_Class_12.html)
    - Practice 8 [Link](LO/Algorithm_Class_13.html)
- Class 6: Heap and Graph Search I  [Link](LO/Algorithm_Class_14.html)
    - Practice 9 [Link](LO/Algorithm_Class_15.html)
- Class 7: Graph Search II - DFS [Link](LO/Algorithm_Class_16.html)
    - Practice 10 [Link](LO/Algorithm_Class_17.html)
    - Practice 11 [Link](LO/Algorithm_Class_18.html)
    - Practice 12 [Link](LO/Algorithm_Class_19.html)
- Class 8: Hash Table and String I [Link](LO/Algorithm_Class_20.html) (pending)
- Class 9: String II [Link](LO/Algorithm_Class_21.html) (pending)
    - Practice 13 [Link](LO/Algorithm_Class_22.html)
    - Practice 14 [Link](LO/Algorithm_Class_23.html) (pending)
- Class 10: Bit [Link](LO/Algorithm_Class_24.html) (pending)
    - Practice 15 [Link](LO/Algorithm_Class_25.html) (pending)
- Class 11: Midterm I [Link](LO/Algorithm_Class_26.html)
    - Practice 16 [Link](LO/Algorithm_Class_27.html) (pending)

## July/2019
<table>
<tr>
  <td>**Mon**</td>
  <td>**Tue**</td>
  <td>**Wed**</td>
  <td>**Thu**</td>
  <td>**Fri**</td>
  <td>**Sat**</td>
  <td>**Sun**</td>
</tr>
<tr>
  <td class="pending">1st  
    [Practice 17](LO/Algorithm_Class_28.html)</td>
  <td></td>
  <td class="pending">3rd  
    [Class 12](LO/Algorithm_Class_29.html)</td>
  <td></td>
  <td class="pending">5th  
    [Class 13](LO/Algorithm_Class_30.html)</td>
  <td class="pending">6th  
    [Design 1](LO/Algorithm_Class_31.html)</td>
  <td class="pending">7th  
    [Practice 18](LO/Algorithm_Class_32.html)</td>
</tr>
<tr>
  <td class="pending">8th  
    [Design 2](LO/Algorithm_Class_33.html)</td>
  <td></td>
  <td class="pending">10th  
    [Class 14](LO/Algorithm_Class_34.html)</td>
  <td></td>
  <td>12th  
    [Class 15](LO/Algorithm_Class_35.html)</td>
  <td class="pending">13th  
    [Class 16](LO/Algorithm_Class_36.html)</td>
  <td class="pending">14th  
    [Class 17](LO/Algorithm_Class_37.html)</td>
</tr>
<tr>
  <td class="pending">15th  
    [Design 3](LO/Algorithm_Class_38.html)</td>
  <td></td>
  <td class="pending">17th  
    [Class 18](LO/Algorithm_Class_39.html)</td>
  <td></td>
  <td class="updated">19th  
    [Design 4](LO/Algorithm_Class_40.html)</td>
  <td>20th  
    [Class 19](LO/Algorithm_Class_41.html)</td>
  <td class="updated">21st  
    [Practice 19](LO/Algorithm_Class_42.html)</td>
</tr>
<tr>
  <td class="updated">22nd  
    [Design 5](LO/Algorithm_Class_43.html)</td>
  <td></td>
  <td class="updated">24th  
    [Design 6](LO/Algorithm_Class_44.html)</td>
  <td></td>
  <td class="pending">26th  
    [Class 20](LO/Algorithm_Class_45.html)</td>
  <td class="pending">27th  
    [Practice 20](LO/Algorithm_Class_46.html)</td>
  <td class="pending">28th  
    Class 21</td>
</tr>
<tr>
  <td class="pending">29th  
    [Practice 21](LO/Algorithm_Class_48.html)</td>
  <td></td>
  <td class="pending">31st  
    [Design 7](LO/Algorithm_Class_49.html)</td>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
</tr>
</table>

- (Continue)
    - Practice 17 [Link](LO/Algorithm_Class_28.html) (pending)
- Class 12: Recursion II [Link](LO/Algorithm_Class_29.html) (pending)
- Class 13: DP I [Link](LO/Algorithm_Class_30.html) (pending)
- Design 1: OOD I [Link](LO/Algorithm_Class_31.html) (pending)
    - Practice 18 [Link](LO/Algorithm_Class_32.html) (pending)
- Design 2: OOD II [Link](LO/Algorithm_Class_33.html) (pending)
- Class 14: DP II [Link](LO/Algorithm_Class_34.html) (pending)
- Class 15: Resume [Link](LO/Algorithm_Class_35.html) (pending)
- Class 16: DP III [Link](LO/Algorithm_Class_36.html) (pending)
- Class 17: Sampling [Link](LO/Algorithm_Class_37.html) (pending)
- Design 3: OOD III [Link](LO/Algorithm_Class_38.html) (pending)
- Class 18: 加强 1 [Link](LO/Algorithm_Class_39.html) (pending)
- Design 4: OOD IV [Link](LO/Algorithm_Class_40.html)
- Class 19: Midterm II [Link](LO/Algorithm_Class_41.html)
    - Practice 19 [Link](LO/Algorithm_Class_42.html)
- Design 5: Overview and Architecture [Link](LO/Algorithm_Class_43.html)
- Design 6: Web Applications [Link](LO/Algorithm_Class_44.html)
- Class 20: 加强 2 [Link](LO/Algorithm_Class_45.html) (pending)
    - Practice 20 [Link](LO/Algorithm_Class_46.html) (pending)
- Class 21: Recursion III [Link](LO/Algorithm_Class_47.html) (pending)
    - Practice 21 [Link](LO/Algorithm_Class_48.html) (pending)
- Design 7: 習題, Web crawler and feed & URL Shortener [Link](LO/Algorithm_Class_49.html) (pending)

## August/2019
<table>
<tr>
  <td>**Mon**</td>
  <td>**Tue**</td>
  <td>**Wed**</td>
  <td>**Thu**</td>
  <td>**Fri**</td>
  <td>**Sat**</td>
  <td>**Sun**</td>
</tr>
<tr>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
  <td class="diagonalRising"></td>
  <td></td>
  <td class="pending">2nd  
    [Class 22](LO/Algorithm_Class_50.html)</td>
  <td class="pending">3rd  
    [Design 8](LO/Algorithm_Class_51.html)</td>
  <td class="pending">4th  
    [Class 23](LO/Algorithm_Class_52.html)</td>
</tr>
<tr>
  <td class="pending">5th  
    [Design 9](LO/Algorithm_Class_53.html)</td>
  <td></td>
  <td class="pending">7th  
    [Practice 22](LO/Algorithm_Class_54.html)</td>
  <td></td>
  <td class="pending">9th  
    [Design 10](LO/Algorithm_Class_55.html)</td>
  <td class="pending">10th  
    [Class 24](LO/Algorithm_Class_56.html)</td>
  <td class="pending">11th  
    [Class 25](LO/Algorithm_Class_57.html)</td>
</tr>
<tr>
  <td class="pending">12th  
    [Class 26](LO/Algorithm_Class_58.html)</td>
  <td></td>
  <td class="pending">14th  
    [Practice 23](LO/Algorithm_Class_59.html)</td>
  <td></td>
  <td class="pending">16th  
    [Class 27](LO/Algorithm_Class_60.html)</td>
  <td class="pending">17th  
    [Practice 24](LO/Algorithm_Class_61.html)</td>
  <td class="pending">18th  
    [Class 28](LO/Algorithm_Class_62.html)</td>
</tr>
<tr>
  <td class="pending">19th  
    [Class 29](LO/Algorithm_Class_63.html)</td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
</tr>
<tr>
  <td></td>
  <td></td>
  <td>28th  
    [X Class 01](LO/Algorithm_Class_64.html)</td>
  <td></td>
  <td>30th  
    [X Class 02](LO/Algorithm_Class_65.html)</td>
  <td></td>
  <td class="diagonalRising"></td>
</tr>
</table>

- Class 22: DFS II [Link](LO/Algorithm_Class_50.html) (pending)
- Design 8: Database Overview [Link](LO/Algorithm_Class_51.html) (pending)
- Class 23: 加强 3 [Link](LO/Algorithm_Class_52.html) (pending)
- Design 9: Database Overview II [Link](LO/Algorithm_Class_53.html) (pending)
    - Practice 22 [Link](LO/Algorithm_Class_54.html) (pending)
- Design 10: Data Processing [Link](LO/Algorithm_Class_55.html) (pending)
- Class 24: 加强 4 [Link](LO/Algorithm_Class_56.html) (pending)
- Class 25: Project [Link](LO/Algorithm_Class_57.html) (pending)
- Class 26: DP IV [Link](LO/Algorithm_Class_58.html) (pending)
    - Practice 23 [Link](LO/Algorithm_Class_59.html) (pending)
- Class 27: Trie [Link](LO/Algorithm_Class_60.html) (pending)
    - Practice 24 [Link](LO/Algorithm_Class_61.html) (pending)
- Class 28: 加課 [Link](LO/Algorithm_Class_62.html) (pending)
- Class 29: Final [Link](LO/Algorithm_Class_63.html) (pending)
- X Class 01: 面試準備 + 理解語義 [Link](LO/Algorithm_Class_64.html) (pending)
- X Class 02

---

# Homework
## Section 1
- Class 1 - Binary Search
    - 1.1. Classical Binary Search
    - 1.2. Binary Search In Sorted 2D Array I
    - 1.3. Closest Number In Sorter Array
    - 1.4. First Occurrence
    - 1.5. Last Occurrence
    - 1.6. K Closest In Sorted Array
    - 1.7. Search In Unknown Sized Sorted Array
- Class 2 - Recursion I and Sorting Algorithms
    - 2.1 Fibonacci Number
    - 2.2 a To The Power Of b
    - 2.3 Selection Sort
    - 2.4 Merge Sort
    - 2.5 Quick Sort
    - 2.6 Move 0s To The End I
    - 2.7 Rainbow Sort
- Class 3 - Linked Lists
    - 3.1 Reverse Linked List
    - 3.2 Find Middle Node Of Linked List
    - 3.3 Check If Linked List Has Cycle
    - 3.4 Insert In Sorted Linked List
    - 3.5 Merge Two Sorted Linked List
    - 3.6 Reorder Linked List
    - 3.7 Partition Linked List
- Class 4 - Queue and Stack
    - 4.1 Sort Numbers In Two Stacks
    - 4.2 Implement Queue By Two Stacks
    - 4.3 Stack With min()
- Class 5 - Binary Tree & Binary Search Tree
    - 5.1 Binary Tree Pre-order Iterative Traversal
    - 5.2 Binary Tree In-order Iterative Traversal
    - 5.3 Binary Tree Post-order Iterative Traversal
    - 5.4 Check If Binary Tree Is Balanced
    - 5.5 Check If Binary Tree Is Symmetric
    - 5.6 Tweaked Identical Binary Trees
    - 5.7 Is Binary Search Tree Or Not
    - 5.8 Get Keys In Binary Search Tree In Given Range
- Class 6 - Heap & Graph Search Algorithm I (BFS)
    - 6.1 K Smallest In Unsorted Array
    - 6.2 Get Keys In Binary Tree Layer By Layer
    - 6.3 Bipartite
    - 6.4 Check If Binary Tree Is Complete
    - 6.5 Kth Smallest Number In Sorted Matrix
- Class 7 - Graph Search Algorithm II (DFS)
    - 7.1 All Subsets I
    - 7.2 All Valid Permutations Of Parentheses I
    - 7.3 Combinations Of Coins
    - 7.4 All Permutations I
- Class 8 - HashTable & String I
    - 8.1 Top K Frequent Words
    - 8.2 Missing Number I
    - 8.3 Common Numbers Of Two Sorted Arrays
    - 8.4 Remove Certain Characters
    - 8.5 Remove All Leading/Trailing/Duplicate Space Characters
    - 8.6 Remove Adjacent Repeated Characters I
    - 8.7 Remove Adjacent Repeated Characters IV
    - 8.8 Determine If One String Is Another’s Substring
- Class 9 - String II
    - 9.1 Reverse String
    - 9.2 Reverse Words In Sentence
    - 9.3 Right Shift By N Characters
    - 9.4 String Replace
    - 9.5 String Shuffling
    - 9.6 All Permutations II (with duplicate characters)
    - 9.7 Compress String II
    - 9.8 Decompress String II
    - 9.9 Longest Substring With Only Unique Characters
    - 9.10 Find All Anagrams Of Short String In A Long String
- Class 10 - Bit Representation and Bit Operation
    - 10.1 Determine If A Number Is Power Of 2
    - 10.2 Number Of Different Bits
    - 10.3 All Unique Characters II
    - 10.4 Reverse Bits
    - 10.5 Hexadecimal Representation

## Section 2
- Class 11 - DFS II
    - 11.1 All Subsequences Of Sorted String (All Subsets II)
    - 11.2 All Valid Permutations Of Parentheses II (L pairs of (), M pairs of [], N pairs of {})
    - 11.3 N Queens
    - 11.4 Generate Random Maze
- Class 12 - Dynamic Programming I
    - 12.1 Longest Ascending Subarray
    - 12.2 Max Product Of Cutting Rope
    - 12.3 Array Hopper I
- Class 13 - Dynamic Programming II
    - 13.1 Array Hopper II
    - 13.2 Largest Subarray Sum
    - 13.3 Dictionary Word
    - 13.4 Edit Distance
    - 13.5 Largest Square Of 1s
- Class 14 - Dynamic Programming III
    - 14.1 Longest Consecutive 1s
    - 14.2 Largest Cross With All 1s
    - 14.3 Largest X With All 1s
    - 14.4 Largest Subsquare Surrounded By 1s
    - 14.5 Largest Submatrix Sum
- Class 15 - Probability, Sampling, Randomization
    - 15.1 Shuffle
    - 15.2 Reservoir Sampling
    - 15.3 Reservoir Sampling With K Samples
    - 15.4 Random7 Using Random5
    - 15.5 Random1000 Using Random5
    - 15.6 Median Tracker Of Data Flow
    - 15.7 95th Percentile
- Class 16 - Recursion II
    - 



---

<center>

Copyright © 2019 Harry Lu. All rights reserved.

</center>
