---
title: <center>Mathematical Beauty</center>
output: html_document
---
#Archimedean Spiral
$$x=(\alpha+\beta\theta)\cos\theta$$
$$y=(\alpha+\beta\theta)\sin\theta$$
Take $\alpha=0$ and $\beta=1$
```{r Archimedean_Spiral,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center",fig.width=8,fig.height=7.8}
library(ggplot2)
theta=seq(from=0,to=10*pi,by=0.01)
alpha=0
beta=1
x=(alpha+beta*theta)*cos(theta)
y=(alpha+beta*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
#  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

#Logarithmic Spirals
$$x=\alpha e^{\beta\theta}\cos\theta$$
$$y=\alpha e^{\beta\theta}\sin\theta$$
Take $\alpha=0.1$ and $\beta=0.1$
```{r Logarithmic_Spiral_1,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center",fig.width=8,fig.height=6.6}
library(ggplot2)
e=exp(1)
theta=seq(from=0,to=10*pi,by=0.01)
alpha=0.1
beta=0.1
x=alpha*e^(beta*theta)*cos(theta)
y=alpha*e^(beta*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
#  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

A special case: when $\beta\approx0.3063489$, the spiral is called a *Golden Spiral*.
```{r Logarithmic_Spiral_2,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center",fig.width=8,fig.height=5}
library(ggplot2)
e=exp(1)
theta=seq(from=0,to=10*pi,by=0.01)
alpha=0.001
beta=0.3063489
x=alpha*e^(beta*theta)*cos(theta)
y=alpha*e^(beta*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
#  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

#Limaçon de Pascal
$$x=(\alpha+\beta\cos\theta)\cos\theta$$
$$y=(\alpha+\beta\cos\theta)\sin\theta$$
Take $\alpha=0.5$ and $\beta=1$
```{r Limacon}
library(ggplot2)
theta=seq(from=0,to=2*pi,by=0.01)
alpha=0.5
beta=1
x=(alpha+beta*cos(theta))*cos(theta)
y=(alpha+beta*cos(theta))*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

#Heart Curve
$$x=\alpha(1-\sin\theta)\cos\theta$$
$$y=\alpha(1-\sin\theta)\sin\theta$$
Take $\alpha=1$
```{r Heart_1,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=2*pi,by=0.01)
a=1
x=a*(1-sin(theta))*cos(theta)
y=a*(1-sin(theta))*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
#  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

$$x=\arccos(\sin\theta)\cdot\cos\theta$$
$$y=\arccos(\sin\theta)\cdot\sin\theta$$
```{r Heart_2,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=2*pi,by=0.01)
x=acos(sin(theta))*cos(theta)
y=acos(sin(theta))*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
#  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

#Rose Curve
$$x=\cos n\theta\cdot\cos\theta$$
$$y=\cos n\theta\cdot\sin\theta$$
Take $n=\frac{2}{3}$
```{r Rose_Curve_1,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=8*pi,by=0.01)
n=2/3
x=cos(n*theta)*cos(theta)
y=cos(n*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

Take $n=\frac{1}{4}$
```{r Rose_Curve_2,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=8*pi,by=0.01)
n=1/4
x=cos(n*theta)*cos(theta)
y=cos(n*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

Take $n=\frac{3}{4}$
```{r Rose_Curve_3,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=8*pi,by=0.01)
n=3/4
x=cos(n*theta)*cos(theta)
y=cos(n*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

Take $n=\frac{2}{5}$
```{r Rose_Curve_4,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=16*pi,by=0.01)
n=2/5
x=cos(n*theta)*cos(theta)
y=cos(n*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

Take $n=\frac{3}{5}$
```{r Rose_Curve_5,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=16*pi,by=0.01)
n=3/5
x=cos(n*theta)*cos(theta)
y=cos(n*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

Take $n=e$
```{r Rose_Curve_6,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=32*pi,by=0.01)
n=exp(1)
x=cos(n*theta)*cos(theta)
y=cos(n*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

Take $n=\pi$
```{r Rose_Curve_7,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=64*pi,by=0.01)
n=pi
x=cos(n*theta)*cos(theta)
y=cos(n*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

Take $n=\sqrt{2}$
```{r Rose_Curve_8,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=64*pi,by=0.01)
n=sqrt(2)
x=cos(n*theta)*cos(theta)
y=cos(n*theta)*sin(theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

#???
$$x=\cos\theta-\cos80\theta\cdot\sin\theta$$
$$y=2\sin\theta-\sin80\theta$$
```{r unknown,message=FALSE,warning=FALSE,echo=FALSE,fig.align="center"}
library(ggplot2)
theta=seq(from=0,to=2*pi,by=0.01)
x=cos(theta)-cos(80*theta)*sin(theta)
y=2*sin(theta)-sin(80*theta)
d=data.frame(x,y)
ggplot(d,aes(x,y))+
  #  geom_point(color="black",size=0.1)+
  geom_path(color="mediumorchid")
```

