---
title: "My favorite music and songs!"
output: html_document
---
<style>
ul {font-family: Times New Roman; font-size: 24px;}
img {display: block; margin-left: auto; margin-right: auto; margin-bottom: 10px;}
bdi {font-size: 12px; color: black;}
@media screen and (min-width:700px) {
  img {width: 50%;}
}
@media screen and (max-width:699px) {
  img {}
  ul {font-size: 20px;}
}
</style>

# Music Sheets{.tabset}
## Summary
Hello! Thanks for visiting my music site!

---

## Self-Arranged Music
I use [MuseScore](https://musescore.com/dashboard) to create the music sheets. Welcome to visit [my profile](https://musescore.com/user/31617737) on MuseScore!

- [Rain Butterfly](Music Sheets/MS_雨蝶.pdf)
- [Time to Say Goodbye](Music Sheets/MS_Time_To_Say_Goodbye.pdf)
- [美麗拍檔](Music Sheets/美麗拍檔.pdf)
- [歌に形はないけれど](Music Sheets/歌に形はないけれど.pdf)
- [一剪梅](Music Sheets/一剪梅.pdf)

---

## Downloads
Acknowledgement [虫虫钢琴](http://www.gangqinpu.com/), [kuroto2000](http://kuroto2000.com/), [MuseScore](https://musescore.com/dashboard), and [Scribd](https://www.scribd.com/) provides all the downloads.

- [理查德克萊德曼 - 夢中的婚禮 Mariage d'Amour](Music Sheets/理查德克萊德曼-夢中的婚禮.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/87.htm)
- [理查德克萊德曼 - 秋日私語 A Comme Amour](Music Sheets/理查德克萊德曼-秋日私語.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/136.htm)
- [理查德克萊德曼 - 柔如彩虹 Couleur Tendresse](Music Sheets/理查德克萊德曼-柔如彩虹.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/229.htm)
- [理查德克萊德曼 - 愛的協奏曲 A Lover's Concerto](Music Sheets/理查德克萊德曼-愛的協奏曲.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/138.htm)
- [理查德克萊德曼 - 玫瑰色的人生 La Vie En Rose](Music Sheets/理查德克萊德曼-玫瑰色的人生.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/137.htm)
- [理查德克萊德曼 - 天鵝 The Swan](Music Sheets/理查德克萊德曼-天鵝.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/52.htm)
- [理查德克萊德曼 - 星空 Lyphard Melodie](Music Sheets/理查德克萊德曼-星空.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/48.htm)
- [理查德克萊德曼 - 愛的克麗絲汀娜(童年的回憶) Souvenir D'enfance](Music Sheets/理查德克萊德曼-愛的克麗絲汀娜.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/156.htm)
- [理查德克萊德曼 - 愛之夢 Leberstraum](Music Sheets/理查德克萊德曼-愛之夢.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/225.htm)
- [理查德克萊德曼 - 給母親的信 Lettre A Ma Mere](Music Sheets/理查德克萊德曼-給母親的信.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/224.htm)
- [理查德克萊德曼 - 愛的旋律 La Vraie Musique de L'Amour](Music Sheets/理查德克萊德曼-愛的旋律.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/227.htm)
- [理查德克萊德曼 - 出埃及記 Exodus](Music Sheets/理查德克萊德曼-出埃及記.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/270.htm)
- [理查德克萊德曼 - 鄉愁(思鄉曲) Nostalgy](Music Sheets/理查德克萊德曼-鄉愁(思鄉曲).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/454.htm)
- [理查德克萊德曼 - 綠袖子 Greensleeves](Music Sheets/理查德克萊德曼-綠袖子.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/510.htm)
- [理查德克萊德曼 - 藍色的愛 Love is Blue](Music Sheets/理查德克萊德曼-藍色的愛.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/528.htm)
- [理查德克萊德曼 - 梁祝](Music Sheets/理查德克萊德曼-梁祝.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/49.htm)
- [理查德克萊德曼 - 水邊的阿狄麗娜(致愛德琳的詩) Ballade pour Adeline](Music Sheets/理查德克萊德曼-水邊的阿狄麗娜.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/33642.htm)
- [理查德克萊德曼 - 羅密歐與朱麗葉 Romeo and Juliet](Music Sheets/理查德克萊德曼-羅密歐與朱麗葉.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/1964.htm)
- [理查德克萊德曼 - 回憶(貓)](Music Sheets/理查德克萊德曼-回憶.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/1112.htm)
- [馬克西姆 - 克羅地亞狂想曲](Music Sheets/克羅地亞狂想曲.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/8612.htm)
- [馬克西姆 - 野蜂飛舞](Music Sheets/野蜂飛舞.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/7833.htm)
- [柴可夫斯基 - 那不勒斯舞曲 Napoli Dance (Piano & Violin)](Music Sheets/柴可夫斯基-那不勒斯舞曲(鋼琴小提琴).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/9061.htm)
- [柴可夫斯基 - 那不勒斯舞曲 Napoli Dance (Piano)](Music Sheets/柴可夫斯基-那不勒斯舞曲(鋼琴).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/7971.htm)
- [貝多芬 - 月光](Music Sheets/貝多芬-月光.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/127.htm)
- [舒伯特 - 小夜曲](Music Sheets/舒伯特-小夜曲.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/22600.htm)
- [維塔斯 - 星星](Music Sheets/維塔斯-星星.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/17086.htm)
- [周傑倫 - 最長的電影](Music Sheets/周傑倫-最長的電影.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/4425.htm)
- [周傑倫 - 最長的電影 (Piano & Other)](Music Sheets/周傑倫-最長的電影(鋼琴+其它).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/6253.htm)
- [周傑倫 - 蒲公英的約定](Music Sheets/周傑倫-蒲公英的約定.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/16018.htm)
- [周傑倫 - 説好的幸福呢](Music Sheets/周傑倫-説好的幸福呢.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/6419.htm)
- [周傑倫 - 菊花臺](Music Sheets/周傑倫-菊花臺.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/35377.htm)
- [歌に形はないけれど(Piano Re-arrange Ver.)](Music Sheets/歌に形はないけれど(Piano Re-arrange Ver.).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/31925.htm)
- [歌に形はないけれど(Orchestral)](Music Sheets/歌に形はないけれど(Orchestral).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/35022.htm)
- [歌に形はないけれど(doriko)](Music Sheets/歌に形はないけれど(doriko).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/14208.htm)
- [歌に形はないけれど(花たん)](Music Sheets/歌に形はないけれど(花たん).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/35183.htm)
- [歌に形はないけれど(MARASY)](Music Sheets/歌に形はないけれど(MARASY).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/18507.htm)
- [Variations on the Kanon by Pachelbel](Music Sheets/Variations on the Kanon by Pachelbel(伊den).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/8331.htm)
- [致青春](Music Sheets/致青春(鸠玖).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/20942.htm)
- [Ave Maria (Harp & Oboe)](Music Sheets/Ave Maria(Harp & Oboe).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/17669.htm)
- [大魚](Music Sheets/大魚.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/29422.htm)
- [愛的供養 (Piano & Flute)](Music Sheets/愛的供養(鋼琴長笛).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/14922.htm)
- [劉若英 - 後來](Music Sheets/劉若英-後來.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/35585.htm)
- [鄧紫棋 - 有多少愛可以重來 (Piano & Flute)](Music Sheets/鄧紫棋-有多少愛可以重來(鋼琴長笛).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/23580.htm)
- [鄧紫棋 - 是否 (Piano & Other)](Music Sheets/鄧紫棋-是否(鋼琴+其它).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/22465.htm)
- [王菲 - 紅豆 (Piano & Other)](Music Sheets/王菲-紅豆(鋼琴+其它).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/18674.htm)
- [王菲 - 紅豆](Music Sheets/王菲-紅豆.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/1037.htm)
- [F4 - 流星雨](Music Sheets/F4-流星雨.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/31727.htm)
- [寂靜之聲](Music Sheets/寂靜之聲.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/2502.htm)
- [玉置浩二 - 冰點](Music Sheets/玉置浩二-冰點.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/35667.htm)
- [但願人長久](Music Sheets/但願人長久.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/16950.htm)
- [名偵探柯南 - 只要有你](Music Sheets/名偵探柯南-只要有你.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/3749.htm)
- [恩雅 - Amarantine](Music Sheets/恩雅-Amarantine.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/12668.htm)
- [美麗的神話 (A♭)](Music Sheets/美麗的神話(降A).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/10406.htm)
- [美麗的神話 (A)](Music Sheets/美麗的神話(A).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/639.htm)
- [巴達爾切夫斯卡 - 少女的祈禱](Music Sheets/巴達爾切夫斯卡-少女的祈禱.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/11819.htm)
- [仰げば尊し](Music Sheets/仰げば尊し.pdf) [<bdi>original</bdi>](https://mahoroba.logical-arts.jp/score/download.php?id=149)
- [那些年](Music Sheets/那些年.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/16375.htm)
- [月半小夜曲](Music Sheets/月半小夜曲.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/20803.htm)
- [五月天 - 突然好想你 (易)](Music Sheets/五月天-突然好想你1.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/26791.htm)
- [五月天 - 突然好想你 (中)](Music Sheets/五月天-突然好想你2.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/20482.htm)
- [五月天 - 突然好想你 (難)](Music Sheets/五月天-突然好想你3.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/31404.htm)
- [五月天 - 突然好想你 (Piano + Other)](Music Sheets/五月天-突然好想你(鋼琴+其它).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/10809.htm)
- [五月天 - 突然好想你 (歌詞)](Music Sheets/五月天-突然好想你(歌詞).pdf) [<bdi>original</bdi>](https://www.hqgq.com/pu/show/27455)
- [蘇苪 - 是否 (Piano + Other)](Music Sheets/蘇苪-是否(鋼琴+其它).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/14776.htm)
- [鄧紫棋 - 光年之外](Music Sheets/鄧紫棋-光年之外.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/30219.htm)
- [鄧紫棋 - 後會無期](Music Sheets/鄧紫棋-後會無期.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/24120.htm)
- [鄧紫棋 - 後會無期 (Piano + Other) (B♭)](Music Sheets/鄧紫棋-後會無期(鋼琴+其它)(降B).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/24486.htm)
- [鄧紫棋 - 後會無期 (Piano + Other) (G)](Music Sheets/鄧紫棋-後會無期(鋼琴+其它)(G).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/27577.htm)
- [鄧紫棋 - 情人 (Piano + Other)](Music Sheets/鄧紫棋-情人(鋼琴+其它).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/29155.htm)
- [Beyond - 情人](Music Sheets/Beyond-情人.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/3989.htm)
- [鄧紫棋 - 烟熏妆](Music Sheets/鄧紫棋-烟熏妆.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/16342.htm)
- [鄧紫棋 - 睡公主](Music Sheets/鄧紫棋-睡公主.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/10731.htm)
- [鄧紫棋 - 你把我灌醉 (Piano + Other)](Music Sheets/鄧紫棋-你把我灌醉(鋼琴+其它).pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/24552.htm)
- [鄧紫棋 - 回憶的沙漏](Music Sheets/.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/.htm)
- [鄧紫棋 - A.I.N.Y.](Music Sheets/.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/.htm)
- [鄧紫棋 - 喜歡你](Music Sheets/.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/.htm)
- [鄧紫棋 - 手心的薔薇](Music Sheets/.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/.htm)
- [鄧紫棋 - 多遠都要在一起](Music Sheets/.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/.htm)
- [光良 - 童話](Music Sheets/光良-童話.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/29568.htm)
- [李翊君 - 雨蝶](Music Sheets/MS_雨蝶.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/33912.htm)
- [沙寶亮 - 暗香](Music Sheets/暗香.pdf) [<bdi>original</bdi>](http://www.gangqinpu.com/html/5005.htm)
- [UM - オーブの祈り](Music Sheets/オーブの祈り.pdf) [<bdi>original</bdi>](http://kuroto2000.com/archives/883/)
- [UM - Shine Your Orb](Music Sheets/Shine Your Orb.pdf) [<bdi>original</bdi>](http://kuroto2000.com/archives/883/)
- [UM - Take Me Higher](Music Sheets/Take Me Higher.pdf) [<bdi>original</bdi>](http://kuroto2000.com/archives/922/)
- [UM - Brave Love, TIGA](Music Sheets/Brave Love, TIGA.pdf) [<bdi>original</bdi>](http://kuroto2000.com/archives/922/)
- [UM - 英雄の詩](Music Sheets/英雄の詩.pdf) [<bdi>original</bdi>](http://kuroto2000.com/archives/924/)
- [Piano Man](Music Sheets/Piano Man.pdf) [<bdi>original</bdi>](https://musescore.com/user/2136241/scores/4650781)
- [Time to Say Goodbye](Music Sheets/MS_Time_To_Say_Goodbye.pdf) [<bdi>original</bdi>](https://www.scribd.com/doc/15247636/Con-Te-Partiro-Time-to-Say-Goodbye-Original)
- [Castlevania - Wood Carving Partita (Piano)](Music Sheets/Castlevania - Wood Carving Partita (Piano).pdf) [<bdi>original</bdi>](https://musescore.com/user/28104096/scores/5010601)
- [Castlevania - Wood Carving Partita (Piano & Flute)](Music Sheets/Castlevania - Wood Carving Partita (Piano & Flute).pdf) [<bdi>original</bdi>](https://musescore.com/user/22289956/scores/5029937)
- [Castlevania - Wood Carving Partita (Guitar)](Music Sheets/Castlevania - Wood Carving Partita (Guitar).pdf) [<bdi>original</bdi>](https://musescore.com/user/30397486/scores/5325224)
- [Castlevania - Bloody Tears (Piano)](Music Sheets/Castlevania - Bloody Tears (Piano).pdf) [<bdi>original</bdi>](https://musescore.com/user/1441356/scores/3401896)
- [Castlevania: Down of Sorrow - Gloomy Memories (Piano)](Music Sheets/Castlevania Down of Sorrow - Gloomy Memories (Piano).pdf) [<bdi>original</bdi>](https://musescore.com/user/14097276/scores/4850036)
- [Castlevania: Symphony of the Night](Music Sheets/Castlevania Symphony of the Night.pdf) [<bdi>original</bdi>](https://musescore.com/jayjaylin/scores/5201769)
- [千百惠 - 走过咖啡屋](Music Sheets/千百惠-走过咖啡屋.pdf) [<bdi>original</bdi>](https://www.gangqinpu.com/cchtml/905688.htm)



- [bloody tears](Music Sheets/test.pdf)
- [](Music Sheets/.pdf) [<bdi>original</bdi>]()

---

## Dadebrayant
[Website](https://www.dadebrayant.com/)

- [A7X - A Little Piece of Heaven](Music Sheets/A7X - A Little Piece of Heaven.pdf)
- [A7X - The Stage](Music Sheets/A7X - The Stage.pdf)
- [A7X - Hail To the King](Music Sheets/A7X - Hail To the King.pdf)
- [A7X - M.I.A.](Music Sheets/A7X - M.I.A..pdf)
- [A7X - Dear God](Music Sheets/A7X - Dear God.pdf)
- [A7X - So Far Away](Music Sheets/A7X - So Far Away (2018).pdf)
- [A7X - Second Heartbeat](Music Sheets/A7X - Second Heartbeat.pdf)

---

# Playlist{.tabset}
## Picked Songs
<font face="Times New Roman" size=5>
1 歌に形はないけれど (Uta ni Katachi wa Nai Keredo)
</font>

<font size=4>
**doriko**'s second, and one of most notable works, a ballad about how songs do not fade with time. It is included on the album *unformed*.

[*reference*](http://vocaloid.wikia.com/wiki/%E6%AD%8C%E3%81%AB%E5%BD%A2%E3%81%AF%E3%81%AA%E3%81%84%E3%81%91%E3%82%8C%E3%81%A9_(Uta_ni_Katachi_wa_Nai_Keredo)#Japanese%20Lyrics)
</font>

<font face="Times New Roman" size=5>
2 愛はバラードのように～ベジータのテーマ～ (Ai wa Barādo no Yō ni~Bejīta no Tēma~)
</font>

<font size=4>
It is a character song for Vegeta performed by **Shin Oya**.

[*reference*](https://wiki2.org/en/Saiky%C3%B4_no_Fusion)
</font>

---

</br>
</br>
</br>

## 1{.tabset}
<center><font face="Times New Roman" size=5>歌に形はないけれど</font></center>

</br>

<div class="two-column"><font size=4><center>

**Japanese (日本語歌詞)**

薄紅の時を彩る花びら  
ひらひら舞う光の中  
僕は笑えたはず

鮮やかな日々に僕らが残した	
砂の城は波に溶けて	
きっと夢が終わる

真っ白な世界で目を覚ませば	
伸ばす腕は何もつかめない	
見上げた空が近くなるほどに	
僕は何を失った？

透通る波	
映る僕らの影は蒼く遠く  
あの日僕は世界を知り  
それは光となった

僕は歌うよ	
笑顔をくれた君が泣いてるとき	
ほんの少しだけでもいい  
君の支えになりたい

僕が泣いてしまった日に  
君がそうだったように

僕がここに忘れたもの	
全て君がくれた宝物	
形のないものだけが	
時の中で色褪せないまま

透通る波	
何度消えてしまっても	
砂の城を僕は君と残すだろう	
そこに光を集め

僕は歌うよ	
笑顔をくれた君が泣いてるとき	
頼りのない僕だけれど	
君のことを守りたい

遠く離れた君のもとへ	
この光が	
空を越えて羽ばたいてゆく	
そんな歌を届けたい

僕が送るものは全て	
形のないものだけど	
君の心の片隅で  
輝く星になりたい

**Romaji (ローマ字)**

usubeni no toki o irodoru hanabira  
hirahira mau hikari no naka  
boku wa waraeta hazu

azayaka na hibi ni bokura ga nokoshita  
suna no shiro wa nami ni tokete  
kitto yume ga owaru

masshiro na sekai de me o samaseba  
nobasu ude wa nani mo tsukamenai  
miageta sora ga chikaku naruhodo ni  
boku wa nani o ushinatta?

sukitooru nami  
utsuru bokura no kage wa aoku tooku  
ano hi boku wa sekai o shiri  
sore wa hikari to natta

boku wa utau yo  
egao o kureta kimi ga naiteru toki  
hon no sukoshi dake de mo ii  
kimi no sasae ni naritai

boku ga naite shimatta hi ni  
kimi ga sou datta you ni

boku ga koko ni wasureta mono  
subete kimi ga kureta takaramono  
katachi no nai mono dake ga  
toki no naka de iroasenai mama

sukitooru nami  
nando kiete shimatte mo  
suna no shiro o boku wa kimi to nokosu darou  
soko ni hikari o atsume

boku wa utau yo  
egao o kureta kimi ga naiteru toki  
tayori no nai boku da keredo  
kimi no koto o mamoritai

tooku hanareta kimi no moto e  
kono hikari ga  
sora o koete habataite yuku  
sonna uta o todoketai

boku ga okuru mono wa subete  
katachi no nai mono dakedo  
kimi no kokoro no katasumi de  
kagayaku hoshi ni naritai

</center></font></div>

### 1. Piano
<center><iframe height="300" src="https://www.youtube.com/embed/rV70FkmXGM8?autoplay=0"></iframe></center>

---

</br>
</br>
</br>

### 2. Instrumental
<center><iframe height="300" src="https://www.youtube.com/embed/XiROef7Q4xs?autoplay=0"></iframe></center>

---

</br>
</br>
</br>

### 3. Vocal (Female)
<center><iframe height="300" src="https://www.youtube.com/embed/Re6JJ_njYR4?autoplay=0"></iframe></center>

---

</br>
</br>
</br>

### 4. Vocal (Male)
<center><iframe height="300" src="https://www.youtube.com/embed/oAgI773mFT4?autoplay=0"></iframe></center>

---

</br>
</br>
</br>

### 5. Music Video
<font face="Times New Roman" size=5>

- [雖然歌聲沒有形狀](http://v.yinyuetai.com/video/2125040), Yinyuetai
- [ONE PIECE - 夢に形はないけれど](https://www.youtube.com/watch?v=PLSnfNZsU3k), Youtube

</font>

</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

---

</br>
</br>
</br>

## 2{.tabset}
<center><font face="Times New Roman" size=5>愛はバラードのように～ベジータのテーマ～</font></center>

</br>

<div class="two-column"><font size=4><center>

**Japanese (日本語歌詞)**

こんな小さな 惑星を  
命を懸けて 守り抜く  
おまえの姿 見るたびに  
馬鹿なヤツだと 思ってた

なぜ？ 無理を承知で  
なぜ？ 傷つきながら  
今日も悪に 立ち向かうのか

★風の中で 雨の中で  
おまえの声が胸の奥 鳴り響く  
バラードのように  
愛のために 夢のために  
プライドさえも投げ捨てて  
俺もまた 戦うのだろう  
迷いながら

鋼の壁を 破いても  
巨大な山を 壊せても  
ほんとの強さじゃないこと  
知っているのは おまえだけ

なぜ？ 鍛えた技も  
なぜ？ 熱い戦闘（バトル）も  
過ぎた後は 虚しいのだろう

風の朝も 雨の夜も  
おまえがくれる微笑みは 暖かい  
バラードのように  
愛のために 夢のために  
そして芽生えた友情に  
俺はただ すべて捧げよう  
おまえとなら

★Repeat

**Chinese (中文歌詞)**

這個小小的星球  
拼上性命去守護  
每次看著你的身影  
就覺得你是個傻瓜

為什麼？明知不可能  
為什麼？即使受了傷  
今天也繼續 直面邪惡

★在風中 在雨中  
你的聲音在胸膛深處鳴響  
如抒情詩一般  
為了愛 為了夢  
連自尊心都捨棄  
我也會 繼續戰鬥吧  
雖然心存猶疑

即使擊穿銅墻鐵壁  
即使破壞巨大山峰  
那不是真正的強大  
只有你明白

為什麼？苦練的招數  
為什麼？激烈的戰鬥  
結束之後 卻是空虛呢

起風的早上 下雨的夜裡  
你給予的微笑很溫暖  
如抒情詩一般  
為了愛 為了夢  
還有萌生的友情  
我唯有 顯出全部  
如果和你一起

★Repeat

</center></font></div>

---

</br>
</br>
</br>
