---
output:
  html_document: default
---
<!--==========================Title==========================-->
</br>
<div class="head-1">Da Lu</div>
<div class="head-2">lvda_1\@163.com&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(413) 559-1266</div>


<!--========================BodyStart========================-->
<body>


<!--=========================================================-->
<!--========================Education========================-->
<!--=========================================================-->
<h1>Education</h1>
<hr/>
<!-------------------------Education 1------------------------->
<div class="education-name">Cornell University</div>
<div class="education-time">Up coming at August 2018</div>
<div class="education-content">
**Degree**: Master of Professional Studies in Applied Statistics  
**Concentration**: Data Science</div>
<!-------------------------Education 2------------------------->
<div class="education-name">University of Massachusetts Amherst</div>
<div class="education-time">September 2013 - May 2017</div>
<div class="education-content">
**Degree**: Bachelor of Science in Mathematics  
**Concentrations**: Applied Mathematics, Statistics, Actuary  
**Minor**: Chemistry</div>
<div class="education-award-name">**Dean’s List**</div>
<div class="education-award-time">January 2014 - January 2017</div>
<div class="education-award-name">**Director Scholarship**</div>
<div class="education-award-time">September 2013 - May 2017</div>


<!--=========================================================-->
<!--=======================Internships=======================-->
<!--=========================================================-->
<h1>Internship Experiences</h1>
<hr/>
<!---------------------------Intern1--------------------------->
<div class="company-research-name">Crane Management Service Inc.</div>
<div class="title">Statistical Analyst of Marketing</div>
<div class="title-time">March 2018 - Present</div>
<div class="content">
- Responsible for completing extensive market research for the company. The research includes logistics, engineering demands, frequency and types of projects, labor unions and their demands, as well as attempting to predict future demands based on the changes faced in the industry regarding cargo ships and their increasing size, ports that will require drastic upgrades and ultimately demand new equipment while also analyzing each ports resources and abilities to perform.
- Tasked with determining industry demand and statistical analysis that will assist in projecting the company's direction in the market place.
- The analysis incorporates financial data with regards to potential profit and loss, and determines the potential gross and net profit of prospective jobs in order to determine the attraction to different locations and corresponding industry demands.
- Rewrote and updated the User Operating Manual of SPMT in order to let the company enter new business areas.
</div>
<!---------------------------Intern2--------------------------->
<div class="company-research-name">Fishmarket Inc.</div>
<div class="title">Website Developer</div>
<div class="title-time">October 2017 - Present</div>
<div class="content">
- Constructed a business website for the company to offer convenient inquiry for customers.
- Maintain and update the website.
</div>
<!---------------------------Intern3--------------------------->
<div class="company-research-name">Fishmarket Inc.</div>
<div class="title">Marketing Analyst</div>
<div class="title-time">September 2017 - December 2017</div>
<div class="content">
- Comprehended working contents that included food production and processing, warehouse management, purchase order and invoice handling, client interview, data processing, accounting and logistics.
- Learned to use QuickBooks and to handle purchase order and invoice.
- Helped organize goods of transportation, manage warehouse, check logistics information, and process cooperation procedures with food retailers, schools and restaurants.
- Completed the trend chart of 1400 products from August 2015 and August 2017 with R.
- Accomplished the measurement, modification and organization of Kentucky Proud Program Vendor Info data.
</div>
<!---------------------------Intern4--------------------------->
<div class="company-research-name">CERNET Education Development Co Ltd, Beijing, China</div>
<div class="title">Marketing Director Assistant</div>
<div class="title-time">July 2015 - August 2015</div>
<div class="content">
- Wrote three marketing research reports in English.
- Published five articles, sharing my own college application preparation experience and my life, on WeChat public platform.
- Organized two successful orientations for high school students and high school graduates.
- Prepared the project launch ceremony of the International Pathway Program.
- Planned the guests (Chinese Education Officials) interview, and the speeches to CERNET executives.
</div>
<!---------------------------Intern5--------------------------->
<div class="company-research-name">Penghua Fund Management Company Ltd, Beijing, China</div>
<div class="title">Business Assistant, Business Department</div>
<div class="title-time">June 2014 - July 2014</div>
<div class="content">
- Negotiated with bank finance department manager following my supervisor, and learned business etiquette.
- Built business data forms, and participated in many meetings with other business departments all over China.
</div>


<!--=========================================================-->
<!--=======================Researches========================-->
<!--=========================================================-->
<h1>Research Experiences</h1>
<hr/>
<!--------------------------Research1-------------------------->
<div class="company-research-name">Are Customer Review Scores Influencing Sale Rankings? A Study on Amazon Best Sellers</div>
<div class="title">Assistant Researcher</div>
<div class="title-time">September 2017 - Present</div>
<div class="content">
- Cooperated with Assistant Professor Fang Tian, Business Administration Division, Seaver College, Pepperdine University
- Applied nonparametric methods to study Amazon Best Sellers to determine customer review scores’ impacts on sales ranking
- Collected and processed data including sales ranking, price, star points, customer average reviews, review numbers and answered questions of selected commodities including Baby Musical Toys and Single Room Humidifiers, conducted Spearman and Kendall tests to evaluate correlation between sales ranking and rest variables and generate correlation charts of relevant tests, and executed Wilcoxon Rank-Sum test to verify derived conclusions.
</div>
<!--------------------------Research2-------------------------->
<div class="company-research-name">Forecasting Straits Times Index Stock Value</div>
<div class="title">Undergraduate Researcher</div>
<div class="title-time">May 2016 - July 2016</div>
<div class="content">
- Cooperated with Associate Prof. Hongkun Zhang, Department of Mathematics and Statistics, UMass Amherst
- Applied simple ARMA model to Google Alphabet stock and analyzed statistically how the data distributes.
- Studied Markov Switching model, ARCH model and GARCH model.
- Applied Markov Switching - AR(1) - GARCH(1,1) model on the STI Index from the Yahoo Finance data (1987/12/28 - 2016/6/14) as well as back-testing to predict future log returns for market close values.
- Classified data into two groups by plotting multiple log return graphs and applied AR(1) - GARCH(1,1) to each section.
- Built a reliable model and predicted almost all the real prices within given price range.
</div>
<!--------------------------Research3-------------------------->
<div class="company-research-name">Study on Measurement Method of Arsenic (As) in Rice with Hach EZ test kit, Tyson's Lab</div>
<div class="title">Undergraduate Researcher</div>
<div class="title-time">September 2013 - December 2015</div>
<div class="content">
- Cooperated with Prof. Julian Tyson, Department of Chemistry, UMass Amherst
- Conducted the research weekly eight hours on average for five semesters from my freshmen year, wrote experimental progress reports, attended weekly meetings to discuss with the professor and group members on next procedures.
- Utilized statistical methods to deal with experimental data, for instance, using statistical distribution constant to describe As content in different rice samples, using ADI Digital Image Analysis to extract RGB value of test strips when analyzing their As content, and using the logarithmic diagrams in Excel to correspond to the colors on test strips and color charts.
- Went through a whole research process, improved my research capacities and academic writing ability, and learned to use statistical methods to serve for experimental analysis.
</div>


<!--=========================================================-->
<!--========================Projects=========================-->
<!--=========================================================-->
<h1>Projects</h1>
<hr/>
<div class="content">
<ul>
<li class="project">Development of Interactive Web Applications using R-Shiny.</li>
<li class="project">Exploration of Different Visualization Techniques of the 'Gapminder' Data using R-Shiny.</li>
<li class="project">Information retrieval on the web and data wrangling (NHL Hockey Schedule, Forbes 100, top 250 movies from IMDb).</li>
<li class="project">Statistical analysis of bird breeding pairs.</li>
</ul>
</div>


<!--=========================================================-->
<!--=======================Activities========================-->
<!--=========================================================-->
<h1>Activities</h1>
<hr/>
<!--------------------------Activity1-------------------------->
<div class="company-research-name">EducationUSA, Embassy of USA, Beijing, China</div>
<div class="title">Guest Speaker</div>
<div class="title-time">June 2014 - August 2016</div>
<div class="content">
- Lectured to coming students and parents on UMass Amherst advantages, college life lessons and study experiences.
- Represented UMass Amherst to give introduction to the college in the college fair.
</div>
<!--------------------------Activity2-------------------------->
<div class="company-research-name">International Programs Office, UMass Amherst</div>
<div class="title">IPO Buddy</div>
<div class="title-time">August 2014 - May 2015</div>
<div class="content">
- Handled daily matters of the office, and offered assistance to international students in choosing courses.
</div>
<!--------------------------Activity3-------------------------->
<div class="company-research-name">Standard Chartered Investing Competition, Young Elite Camp, Beijing, China</div>
<div class="title">Group Leader</div>
<div class="title-time">July 2015</div>
<div class="content">
- Motivated and led group members to solve challenging financial problems and decided the best way of investing money.
- Learned British Royal Family Etiquette, and completed mock interviews
</div>


<!--=========================================================-->
<!--========================Teaching=========================-->
<!--=========================================================-->
<h1>Teaching Experiences</h1>
<hr/>
<!--------------------------Teaching1-------------------------->
<div class="company-research-name">UMass Amherst</div>
<div class="title">Private Tutor</div>
<div class="title-time">September 2013 - May 2017</div>
<div class="content">
- Subjects: Calculus, Linear Algebra, Ordinary Differential Equation, Probability, Statistics, Chemistry, R programming.
- Tutored students in need these subjects generally two hours per week and 3-4 students each year.
- Tutored a student on Calculus I in Spring 2017, helped her improve grade from F to A-.
</div>
<!--------------------------Teaching2-------------------------->
<div class="company-research-name">East Asian Languages and Cultures Program, UMass Amherst</div>
<div class="title">Chinese Tutor</div>
<div class="title-time">January 2015 - December 2015</div>
<div class="content">
- Communicated and learned Chinese grammar and teaching skills with head tutor every week.
- Created new ideas to the dean of Chinese Program on how to improve the program.
- Tutored Chinese Major students pronunciation, grammar, writing and speaking.
</div>


<!--=========================================================-->
<!--=========================Skills==========================-->
<!--=========================================================-->
<h1>Skills</h1>
<hr/>
<div class="content">
- Computer Languages: R, SQL, Markdown, HTML, CSS, Java, Python.
- Computer Software: RStudio, Microsoft PowerPoint, Microsoft Excel, Microsoft Word, Adobe Photoshop.
- Languages: Fluent in both Mandarin and English.
- Data Analysis: Descriptive Analysis, Statistical Modeling, Time Series Analysis (ARIMAX, SARIMA, GARCH), Data Visualization, Optimization
</div>


<!--========================Body End=========================-->
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</body>

<!--=========================================================-->
<!--==========================STYLE==========================-->
<!--=========================================================-->
<style>
@media screen and (min-width:1024px) {
  body {
    font-family: Times New Roman;
  }
  h1 {
    font-size: 32px;
    font-weight: bold;
    width: 100%;
  }
  ul {
    font-size: 16px;
    margin-top: 0px;
    margin-bottom: 0px;
  }
  hr {
    border: 0;
    height: 2px;
    margin-top: -5px;
    margin-bottom: 0px;
    background: black;
    width: 910px;
  }
  li {
    margin-top: 0px;
    font-size: 16px;
    text-align: justify;
  }
  li.project {
    font-size: 20px;
    margin-left: 0%;
  }
  .head-1 {
    font-family: Times New Roman;
    font-size: 32px;
    font-weight: bold;
    text-align: center;
  }
  .head-2 {
    font-family: Times New Roman;
    font-size: 16px;
    font-weight: normal;
    text-align: center;
  }
  .education-name {
    font-size: 22px;
    font-weight: bold;
    text-align: left;
    float: left;
    width: 65%;
  }
  .education-time {
    font-size: 22px;
    font-weight: bold;
    text-align: right;
    float: right;
    width: 35%;
  }
  .education-content {
    font-size: 16px;
    font-weight: normal;
    text-align: left;
    margin-left: 5%;
    float: left;
    width: 95%;
  }
  .education-award-name {
    font-size: 16px;
    font-weight: normal;
    text-align: left;
    margin-left: 5%;
    float: left;
    width: 45%;
  }
  .education-award-time {
    font-size: 16px;
    font-weight: bold;
    text-align: right;
    float: right;
    width: 50%;
  }
  .company-research-name {
    font-size: 22px;
    font-weight: bold;
    text-align: left;
    float: left;
    width: 100%;
  }
  .title {
    font-size: 20px;
    font-weight: bold;
    text-align: left;
    margin-left: 5%;
    float: left;
    width: 55%;
  }
  .title-time {
    font-size: 20px;
    font-weight: bold;
    text-align: right;
    float: right;
    width: 40%;
  }
  .content {
    font-size: 16px;
    font-weight: normal;
    margin-left: 5%;
    float: left;
    width: 95%;
  }
}
@media screen and (min-width:600px) and (max-width:1023px) {
  body {
    font-family: Times New Roman;
  }
  h1 {
    font-size: 28px;
    font-weight: bold;
    width: 100%;
  }
  ul {
    font-size: 16px;
    margin-top: 0px;
    margin-bottom: 0px;
  }
  hr {
    border: 0;
    height: 2px;
    margin-top: -5px;
    margin-bottom: 0px;
    background: black;
    width: 100%;
  }
  li {
    margin-top: 0px;
    font-size: 16px;
    text-align: justify;
  }
  li.project {
    font-size: 20px;
    margin-left: 0%;
  }
  .head-1 {
    font-family: Times New Roman;
    font-size: 28px;
    font-weight: bold;
    text-align: center;
  }
  .head-2 {
    font-family: Times New Roman;
    font-size: 16px;
    font-weight: normal;
    text-align: center;
  }
  .education-name {
    font-size: 20px;
    font-weight: bold;
    text-align: left;
    float: left;
    width: 100%;
  }
  .education-time {
    font-size: 20px;
    font-weight: bold;
    text-align: right;
    float: right;
    width: 100%;
  }
  .education-content {
    font-size: 16px;
    font-weight: normal;
    text-align: left;
    margin-left: 5%;
    float: left;
    width: 95%;
  }
  .education-award-name {
    font-size: 16px;
    font-weight: normal;
    text-align: left;
    margin-left: 5%;
    float: left;
    width: 45%;
  }
  .education-award-time {
    font-size: 16px;
    font-weight: bold;
    text-align: right;
    float: right;
    width: 50%;
  }
  .company-research-name {
    font-size: 20px;
    font-weight: bold;
    text-align: left;
    float: left;
    width: 100%;
  }
  .title {
    font-size: 16px;
    font-weight: bold;
    text-align: left;
    margin-left: 5%;
    float: left;
    width: 50%;
  }
  .title-time {
    font-size: 16px;
    font-weight: bold;
    text-align: right;
    float: right;
    width: 45%;
  }
  .content {
    font-size: 16px;
    font-weight: normal;
    margin-left: 5%;
    float: left;
    width: 95%;
  }
}
@media screen and (max-width:599px) {
  body {
    font-family: Times New Roman;
  }
  h1 {
    font-size: 22px;
    font-weight: bold;
    width: 100%;
  }
  ul {
    font-size: 16px;
    margin-top: 0px;
    margin-bottom: 0px;
  }
  hr {
    border: 0;
    height: 2px;
    margin-top: -5px;
    margin-bottom: 0px;
    background: black;
    width: 100%;
  }
  li {
    margin-top: 0px;
    font-size: 16px;
    text-align: justify;
  }
  li.project {
    margin-left: 0%;
  }
  .head-1 {
    font-family: Times New Roman;
    font-size: 28px;
    font-weight: bold;
    text-align: center;
  }
  .head-2 {
    font-family: Times New Roman;
    font-size: 16px;
    font-weight: normal;
    text-align: center;
  }
  .education-name {
    font-size: 20px;
    font-weight: bold;
    text-align: left;
    float: left;
    width: 100%;
  }
  .education-time {
    font-size: 20px;
    font-weight: bold;
    text-align: right;
    float: right;
    width: 100%;
  }
  .education-content {
    font-size: 16px;
    font-weight: normal;
    text-align: left;
    margin-left: 0%;
    float: left;
    width: 100%;
  }
  .education-award-name {
    font-size: 16px;
    font-weight: normal;
    text-align: left;
    margin-left: 0%;
    float: left;
    width: 100%;
  }
  .education-award-time {
    font-size: 16px;
    font-weight: bold;
    text-align: right;
    float: right;
    width: 100%;
  }
  .company-research-name {
    font-size: 20px;
    font-weight: bold;
    text-align: left;
    float: left;
    width: 100%;
  }
  .title {
    font-size: 16px;
    font-weight: bold;
    text-align: left;
    margin-left: 5%;
    float: left;
    width: 100%;
  }
  .title-time {
    font-size: 16px;
    font-weight: bold;
    text-align: right;
    float: right;
    width: 100%;
  }
  .content {
    font-size: 16px;
    font-weight: normal;
    margin-left: 0%;
    float: left;
    width: 100%;
  }
}
</style>